/*
 * Copyright (C) Ascensio System SIA 2012-2020. All rights reserved
 *
 * https://www.onlyoffice.com/
 *
 * Version: 0.0.0 (build:0)
 */

(function(f,e){function Qa(e){return Wc.locateFile?Wc.locateFile(e,$e):$e+e}function ab(e){var f=Yd[de>>2];e=f+e+15&-16;if(e<=Zd)Yd[de>>2]=e;else if(!Lc(e))return 0;return f}function bb(e,f,w){var Oa=f+w;for(w=f;e[w]&&!(w>=Oa);)++w;if(16<w-f&&e.subarray&&Ve)return Ve.decode(e.subarray(f,w));for(Oa="";f<w;){var Ia=e[f++];if(Ia&128){var Ra=e[f++]&63;if(192==(Ia&224))Oa+=String.fromCharCode((Ia&31)<<6|Ra);else{var Da=e[f++]&63;Ia=224==(Ia&240)?(Ia&15)<<12|Ra<<6|Da:(Ia&7)<<18|Ra<<12|Da<<6|e[f++]&63;65536>
Ia?Oa+=String.fromCharCode(Ia):(Ia-=65536,Oa+=String.fromCharCode(55296|Ia>>10,56320|Ia&1023))}}else Oa+=String.fromCharCode(Ia)}return Oa}function fb(e,f){0<e%f&&(e+=f-e%f);return e}function Da(){Wc.HEAP8=ee=new Int8Array(bh);Wc.HEAP16=new Int16Array(bh);Wc.HEAP32=Yd=new Int32Array(bh);Wc.HEAPU8=Ie=new Uint8Array(bh);Wc.HEAPU16=new Uint16Array(bh);Wc.HEAPU32=new Uint32Array(bh);Wc.HEAPF32=new Float32Array(bh);Wc.HEAPF64=new Float64Array(bh)}function Ha(f){for(;0<f.length;){var w=f.shift();if("function"==
typeof w)w();else{var Oa=w.func;"number"===typeof Oa?w.vQf===e?Wc.dynCall_v(Oa):Wc.dynCall_vi(Oa,w.vQf):Oa(w.vQf===e?null:w.vQf)}}}function vb(e){return String.prototype.startsWith?e.startsWith("data:application/octet-stream;base64,"):0===e.indexOf("data:application/octet-stream;base64,")}function Ab(){try{if(Wc.wasmBinary)return new Uint8Array(Wc.wasmBinary);if(Wc.readBinary)return Wc.readBinary(Ne);throw"both async and sync fetching of the wasm failed";}catch(Oa){Ra(Oa)}}function Xa(){return Wc.wasmBinary||
!dg&&!Xe||"function"!==typeof fe?new Promise(function(e){e(Ab())}):fe(Ne,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+Ne+"'";return e.arrayBuffer()}).catch(function(){return Ab()})}function mb(e){function f(e){Wc.asm=e.exports;Eg--;Wc.monitorRunDependencies&&Wc.monitorRunDependencies(Eg);0==Eg&&(null!==Md&&(clearInterval(Md),Md=null),Gf&&(e=Gf,Gf=null,e()))}function w(e){f(e.instance)}function Oa(e){wf().then(function(e){return WebAssembly.instantiate(e,
Ia)}).then(e,function(e){sh("failed to asynchronously prepare wasm: "+e);Ra(e)})}var Ia={env:e,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:Mf};Eg++;Wc.monitorRunDependencies&&Wc.monitorRunDependencies(Eg);if(Wc.instantiateWasm)try{return Wc.instantiateWasm(Ia,f)}catch(Bj){return sh("Module.instantiateWasm callback failed with error: "+Bj),!1}Wc.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||vb(Ne)||"function"!==typeof fe?Oa(w):WebAssembly.instantiateStreaming(fe(Ne,
{credentials:"same-origin"}),Ia).then(w,function(e){sh("wasm streaming compile failed: "+e);sh("falling back to ArrayBuffer instantiation");Oa(w)});return{}}function Sa(e){if(Sa.xKg){var f=Yd[e>>2];var w=Yd[f>>2]}else Sa.xKg=!0,Be.USER=Be.LOGNAME="web_user",Be.PATH="/",Be.PWD="/",Be.HOME="/home/web_user",Be.LANG="C.UTF-8",Be._=Wc.thisProgram,w=Cc?Id(1024):ab(1024),f=Cc?Id(256):ab(256),Yd[f>>2]=w,Yd[e>>2]=f;e=[];var Oa=0,Ia;for(Ia in Be)if("string"===typeof Be[Ia]){var Ra=Ia+"="+Be[Ia];e.push(Ra);
Oa+=Ra.length}if(1024<Oa)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(Ia=0;Ia<e.length;Ia++){Oa=Ra=e[Ia];for(var Da=w,Ha=0;Ha<Oa.length;++Ha)ee[Da++>>0]=Oa.charCodeAt(Ha);ee[Da>>0]=0;Yd[f+4*Ia>>2]=w;w+=Ra.length+1}Yd[f+4*e.length>>2]=0}function Lb(e,f){tc(e,f||1);throw"longjmp";}function Lc(e){if(2147418112<e)return!1;for(var f=Math.max(Zd,16777216);f<e;)f=536870912>=f?fb(2*f,65536):Math.min(fb((3*f+2147483648)/4,65536),2147418112);e=fb(f,65536);var w=Wc.buffer.byteLength;try{var Oa=
-1!==od.grow((e-w)/65536)?Wc.buffer=od.buffer:null}catch(yk){Oa=null}if(!Oa||Oa.byteLength!=f)return!1;Wc.buffer=bh=Oa;Da();Zd=f;return!0}function jc(e){if(0===e)return 0;e=e?bb(Ie,e,void 0):"";if(!Be.hasOwnProperty(e))return 0;jc.Y2f&&Je(jc.Y2f);e=Be[e];for(var f=0,w=0;w<e.length;++w){var Oa=e.charCodeAt(w);55296<=Oa&&57343>=Oa&&(Oa=65536+((Oa&1023)<<10)|e.charCodeAt(++w)&1023);127>=Oa?++f:f=2047>=Oa?f+2:65535>=Oa?f+3:f+4}var Ia=f+1;if(f=Id(Ia))if(w=ee,Oa=f,0<Ia){Ia=Oa+Ia-1;for(var Ra=0;Ra<e.length;++Ra){var Da=
e.charCodeAt(Ra);if(55296<=Da&&57343>=Da){var Ha=e.charCodeAt(++Ra);Da=65536+((Da&1023)<<10)|Ha&1023}if(127>=Da){if(Oa>=Ia)break;w[Oa++]=Da}else{if(2047>=Da){if(Oa+1>=Ia)break;w[Oa++]=192|Da>>6}else{if(65535>=Da){if(Oa+2>=Ia)break;w[Oa++]=224|Da>>12}else{if(Oa+3>=Ia)break;w[Oa++]=240|Da>>18;w[Oa++]=128|Da>>12&63}w[Oa++]=128|Da>>6&63}w[Oa++]=128|Da&63}}w[Oa]=0}jc.Y2f=f;return jc.Y2f}function mc(e){this.name="ExitStatus";this.message="Program terminated with exit("+e+")";this.status=e}function nb(){function e(){if(!Wc.calledRun&&
(Wc.calledRun=!0,!nc)){Cc||(Cc=!0,Ha(cj));Ha(Xg);if(Wc.onRuntimeInitialized)Wc.onRuntimeInitialized();if(Wc.postRun)for("function"==typeof Wc.postRun&&(Wc.postRun=[Wc.postRun]);Wc.postRun.length;)ob.unshift(Wc.postRun.shift());Ha(ob)}}if(!(0<Eg)){if(Wc.preRun)for("function"==typeof Wc.preRun&&(Wc.preRun=[Wc.preRun]);Wc.preRun.length;)sd.unshift(Wc.preRun.shift());Ha(sd);0<Eg||Wc.calledRun||(Wc.setStatus?(Wc.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Wc.setStatus("")},1);e()},
1)):e())}}function Ra(f){if(Wc.onAbort)Wc.onAbort(f);f!==e?(Of(f),sh(f),f=JSON.stringify(f)):f="";nc=!0;throw"abort("+f+"). Build with -s ASSERTIONS=1 for more info.";}function Ia(){this.iVd=this.uLc=this.n2b=this.mL=this.eCc=this.VZ=this.height=this.zZ=this.z5=this.MQa=0;this.KDa=this.N4="";this.Clg=this.Dlg=this.fqg=this.hqg=this.gqg=this.$0f=this.Z0f=this.iqg=this.b1f=this.a1f=this.eqg=this.jqg=this.DDf=0;this.XCf=[]}function Gb(){this.vKc=this.NAc=this.UDa=this.dFa=this.Aka=this.Kqa=this.mua=
this.ela=this.height=this.width=this.Rgg=this.Pgg=this.Sgg=this.Qgg=0}function ge(){this.mode=this.pitch=this.rows=this.width=this.top=this.left=0}var je=f.AscFonts,fe=f.fetch,wf=null;f.AscDesktopEditor&&document.currentScript&&0==document.currentScript.src.indexOf("file:///")?(fe=e,wf=function(){var e="ascdesktop://fonts/"+Ne.substr(8);return new Promise(function(f){var w=new XMLHttpRequest;w.open("GET",e,!0);w.responseType="arraybuffer";w.overrideMimeType?w.overrideMimeType("text/plain; charset=x-user-defined"):
w.setRequestHeader("Accept-Charset","x-user-defined");w.onload=function(){200==this.status&&f(new Uint8Array(this.response))};w.send(null)})}):wf=function(){return Xa()};var Wc="undefined"!==typeof Wc?Wc:{},Oi={},rd;for(rd in Wc)Wc.hasOwnProperty(rd)&&(Oi[rd]=Wc[rd]);Wc.arguments=[];Wc.thisProgram="./this.program";Wc.quit=function(e,f){throw f;};Wc.preRun=[];Wc.postRun=[];var dg=!0,Xe=!1,$e="";if(dg||Xe)Xe?$e=self.location.href:document.currentScript&&($e=document.currentScript.src),$e=0!==$e.indexOf("blob:")?
$e.substr(0,$e.lastIndexOf("/")+1):"",Wc.read=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.send(null);return f.responseText},Xe&&(Wc.readBinary=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.responseType="arraybuffer";f.send(null);return new Uint8Array(f.response)}),Wc.readAsync=function(e,f,w){var Oa=new XMLHttpRequest;Oa.open("GET",e,!0);Oa.responseType="arraybuffer";Oa.onload=function(){200==Oa.status||0==Oa.status&&Oa.response?f(Oa.response):w()};Oa.onerror=w;Oa.send(null)},
Wc.setWindowTitle=function(e){document.title=e};var Of=Wc.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof e?e:null),sh=Wc.printErr||("undefined"!==typeof e?e:"undefined"!==typeof console&&console.warn.bind(console)||Of);for(rd in Oi)Oi.hasOwnProperty(rd)&&(Wc[rd]=Oi[rd]);Oi=e;var Mf={"f64-rem":function(e,f){return e%f},"debugger":function(){debugger}},Fb=0;"object"!==typeof WebAssembly&&sh("no native wasm support detected");var nc=!1,Ve="undefined"!==typeof TextDecoder?
new TextDecoder("utf8"):e;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ee,Ie,Yd,de=109360,Zd=Wc.TOTAL_MEMORY||16777216;5242880>Zd&&sh("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Zd+"! (TOTAL_STACK=5242880)");if(Wc.buffer)var bh=Wc.buffer;else{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory){var od=new WebAssembly.Memory({initial:Zd/65536});bh=od.buffer}else bh=new ArrayBuffer(Zd);Wc.buffer=bh}Da();Yd[de>>2]=5352496;var sd=[],cj=[],Xg=[],ob=
[function(){f.AscFonts.wEb()}],Cc=!1,Eg=0,Md=null,Gf=null;Wc.preloadedImages={};Wc.preloadedAudios={};var Ne="fonts.wasm";vb(Ne)||(Ne=Qa(Ne));Wc.asm=function(e,f){f.memory=od;f.table=new WebAssembly.Table({initial:814,maximum:814,element:"anyfunc"});f.__memory_base=1024;f.__table_base=0;return mb(f)};cj.push({func:function(){ud()}});var Be={},Zb={SPa:[null,[],[]],FRg:function(e,f){var w=Zb.SPa[e];0===f||10===f?((1===e?Of:sh)(bb(w,0)),w.length=0):w.push(f)},ILc:0,get:function(){Zb.ILc+=4;return Yd[Zb.ILc-
4>>2]},E1a:function(){var e=Zb.get();return e?bb(Ie,e,void 0):""},kZg:function(){var e=Zb.get();Zb.get();return e},pZg:function(){Zb.get()}};Oi=Wc.asm({},{b:Ra,e:function(e){Fb=e},d:function(){return Fb},r:function(e,f,w){var Oa=Fg();try{return Ln(e,f,w)}catch(yk){Ae(Oa);if(yk!==yk+0&&"longjmp"!==yk)throw yk;tc(1,0)}},q:function(e,f,w,Ia){var Oa=Fg();try{return dj(e,f,w,Ia)}catch(Bj){Ae(Oa);if(Bj!==Bj+0&&"longjmp"!==Bj)throw Bj;tc(1,0)}},p:function(e,f,w,Ia,Ra){var Oa=Fg();try{return Pi(e,f,w,Ia,
Ra)}catch(Mo){Ae(Oa);if(Mo!==Mo+0&&"longjmp"!==Mo)throw Mo;tc(1,0)}},o:function(e,f,w){var Oa=Fg();try{Uj(e,f,w)}catch(yk){Ae(Oa);if(yk!==yk+0&&"longjmp"!==yk)throw yk;tc(1,0)}},n:function(e,f,Ia,Ra,Da){var Oa=Fg();try{w(e,f,Ia,Ra,Da)}catch(Mo){Ae(Oa);if(Mo!==Mo+0&&"longjmp"!==Mo)throw Mo;tc(1,0)}},m:Sa,l:function(){},k:function(e){Wc.___errno_location&&(Yd[Wc.___errno_location()>>2]=e);return e},A:function(f,w){Zb.ILc=w;try{var Oa=Zb.Xkg();Zb.get();var Ia=Zb.get(),Da=Zb.get(),Ha=Zb.get();e.FZg(Oa,
Ia,Ha);Yd[Da>>2]=Oa.position;Oa.jPg&&0===Ia&&0===Ha&&(Oa.jPg=null);return 0}catch(Mo){return"undefined"!==typeof e&&Mo instanceof e.Bsf||Ra(Mo),-Mo.Byf}},z:function(f,w){Zb.ILc=w;try{var Oa=Zb.Xkg(),Ia=Zb.get(),Da=Zb.get();return Zb.$Yg(Oa,Ia,Da)}catch(Bj){return"undefined"!==typeof e&&Bj instanceof e.Bsf||Ra(Bj),-Bj.Byf}},j:function(f,w){Zb.ILc=w;try{var Oa=Zb.get(),Ia=Zb.get(),Da=Zb.get();for(w=f=0;w<Da;w++){for(var Ha=Yd[Ia+8*w>>2],Sa=Yd[Ia+(8*w+4)>>2],Xa=0;Xa<Sa;Xa++)Zb.FRg(Oa,Ie[Ha+Xa]);f+=Sa}return f}catch(Qi){return"undefined"!==
typeof e&&Qi instanceof e.Bsf||Ra(Qi),-Qi.Byf}},f:function(e,f){Zb.ILc=f;return 0},y:function(f,w){Zb.ILc=w;try{var Oa=Zb.E1a(),Ia=Zb.get(),Da=Zb.get();return e.open(Oa,Ia,Da).eZg}catch(Bj){return"undefined"!==typeof e&&Bj instanceof e.Bsf||Ra(Bj),-Bj.Byf}},i:function(e,f){Zb.ILc=f;return 0},h:function(f,w){Zb.ILc=w;try{var Oa=Zb.Xkg();e.close(Oa);return 0}catch(qm){return"undefined"!==typeof e&&qm instanceof e.Bsf||Ra(qm),-qm.Byf}},g:function(){},x:function(){return Zd},w:function(e,f){Lb(e,f)},
v:function(e,f,w){Ie.set(Ie.subarray(f,f+w),e)},u:Lc,t:jc,c:Lb,s:function(){Ra("OOM")},a:de},bh);Wc.asm=Oi;Wc._ASC_FT_Free=function(){return Wc.asm.B.apply(null,arguments)};Wc._ASC_FT_GetFaceInfo=function(){return Wc.asm.C.apply(null,arguments)};Wc._ASC_FT_GetFaceMaxAdvanceX=function(){return Wc.asm.D.apply(null,arguments)};Wc._ASC_FT_GetKerningX=function(){return Wc.asm.E.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Measure_Params=function(){return Wc.asm.F.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Render_Buffer=
function(){return Wc.asm.G.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Render_Params=function(){return Wc.asm.H.apply(null,arguments)};Wc._ASC_FT_Glyph_Get_CBox=function(){return Wc.asm.I.apply(null,arguments)};Wc._ASC_FT_Init=function(){return Wc.asm.J.apply(null,arguments)};Wc._ASC_FT_Malloc=function(){return Wc.asm.K.apply(null,arguments)};Wc._ASC_FT_Open_Face=function(){return Wc.asm.L.apply(null,arguments)};Wc._ASC_FT_SetCMapForCharCode=function(){return Wc.asm.M.apply(null,arguments)};Wc._ASC_FT_Set_Transform=
function(){return Wc.asm.N.apply(null,arguments)};Wc._ASC_FT_Set_TrueType_HintProp=function(){return Wc.asm.O.apply(null,arguments)};Wc._FT_Done_Face=function(){return Wc.asm.P.apply(null,arguments)};Wc._FT_Done_FreeType=function(){return Wc.asm.Q.apply(null,arguments)};Wc._FT_Get_Glyph=function(){return Wc.asm.R.apply(null,arguments)};Wc._FT_Load_Glyph=function(){return Wc.asm.S.apply(null,arguments)};Wc._FT_Set_Char_Size=function(){return Wc.asm.T.apply(null,arguments)};Wc._FT_Set_Transform=function(){return Wc.asm.U.apply(null,
arguments)};var ud=Wc.___emscripten_environ_constructor=function(){return Wc.asm.V.apply(null,arguments)},Je=Wc._free=function(){return Wc.asm.W.apply(null,arguments)},Id=Wc._malloc=function(){return Wc.asm.X.apply(null,arguments)},tc=Wc._setThrew=function(){return Wc.asm.Y.apply(null,arguments)},Ae=Wc.stackRestore=function(){return Wc.asm.da.apply(null,arguments)},Fg=Wc.stackSave=function(){return Wc.asm.ea.apply(null,arguments)},Ln=Wc.dynCall_iii=function(){return Wc.asm.Z.apply(null,arguments)},
dj=Wc.dynCall_iiii=function(){return Wc.asm._.apply(null,arguments)},Pi=Wc.dynCall_iiiii=function(){return Wc.asm.$.apply(null,arguments)};Wc.dynCall_vi=function(){return Wc.asm.aa.apply(null,arguments)};var Uj=Wc.dynCall_vii=function(){return Wc.asm.ba.apply(null,arguments)},w=Wc.dynCall_viiii=function(){return Wc.asm.ca.apply(null,arguments)};Wc.asm=Oi;mc.prototype=Error();mc.prototype.constructor=mc;Gf=function Jm(){Wc.calledRun||nb();Wc.calledRun||(Gf=Jm)};Wc.run=nb;Wc.abort=Ra;if(Wc.preInit)for("function"==
typeof Wc.preInit&&(Wc.preInit=[Wc.preInit]);0<Wc.preInit.length;)Wc.preInit.pop()();Wc.noExitRuntime=!0;nb();f.AscFonts=f.AscFonts||{};je=f.AscFonts;je.cvg=function(){return Wc._ASC_FT_Init()};je.Qyg=35;je.$Xg=38;je.Ryg=40;je.awg=function(e,f){Wc._ASC_FT_Set_TrueType_HintProp(e,f)};je.dvg=function(e){var f=Wc._ASC_FT_Malloc(e.size);Wc.HEAP8.set(e.data,f);return{LHg:!0,data:f,li:e.size}};je.zPd=function(e){var f=je.m5b[e];f&&!0!==f.LHg&&(f=je.dvg(je.m5b[e]),je.m5b[e]=null,je.m5b[e]=f)};Ia.prototype.load=
function(e){if(e=Wc._ASC_FT_GetFaceInfo(e)){var f=new Int32Array(Wc.HEAP8.buffer,e,Math.min(Wc.HEAP8.length-e>>2,250)),w=0;this.MQa=Math.abs(f[w++]);this.z5=f[w++];this.zZ=f[w++];this.height=f[w++];this.VZ=f[w++];this.eCc=f[w++];this.mL=f[w++];this.n2b=f[w++];this.uLc=f[w++];this.iVd=f[w++];for(var Ia=f[w++];Ia;)this.N4+=String.fromCharCode(Ia),Ia=f[w++];for(Ia=f[w++];Ia;)this.KDa+=String.fromCharCode(Ia),Ia=f[w++];this.DDf=f[w++];this.jqg=f[w++];this.eqg=f[w++];this.a1f=f[w++];this.b1f=f[w++];this.iqg=
f[w++];this.Z0f=f[w++];this.$0f=f[w++];this.gqg=f[w++];w++;this.hqg=je.dU.aQ(f[w++]);w++;w++;w++;w++;this.fqg=f[w++];this.Dlg=f[w++];this.Clg=f[w++];Ia=f[w++];for(var Ra=0;Ra<Ia;Ra++)this.XCf.push(f[w++]);Wc._ASC_FT_Free(e)}};je.hug=Ia;je.sWg=Gb;je.rWg=ge;je.fJf=function(e,f,w){return Wc._ASC_FT_Open_Face(e,f.data,f.li,w)};je.Qvg=function(e,f,w){e=Wc._ASC_FT_Get_Glyph_Measure_Params(e,f?1:0);if(!e)return null;var Ia=15;f&&(Ia=Wc.HEAP32[e>>2]);var Ra=new Int32Array(Wc.HEAP8.buffer,e,4*Ia),Da=new Gb;
Da.Qgg=Ra[1];Da.Sgg=Ra[2];Da.Pgg=Ra[3];Da.Rgg=Ra[4];Da.width=Ra[5];Da.height=Ra[6];Da.ela=Ra[7];Da.mua=Ra[8];Da.Kqa=Ra[9];Da.Aka=Ra[10];Da.dFa=Ra[11];Da.UDa=Ra[12];Da.NAc=Ra[13];Da.vKc=Ra[14];if(f){w.start(f);for(var Ha=15;Ha<Ia;)switch(Ra[Ha++]){case 0:w.Ddg(Ra[Ha++],Ra[Ha++],f);break;case 1:w.vdg(Ra[Ha++],Ra[Ha++],f);break;case 2:w.Mcg(Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],f);break;case 3:w.Pcg(Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],f)}w.end(f)}Wc._ASC_FT_Free(e);return Da};je.E9f=
function(e,f){e=Wc._ASC_FT_Get_Glyph_Render_Params(e,f);if(!e)return null;f=new Int32Array(Wc.HEAP8.buffer,e,24);var w=new ge;w.left=f[0];w.top=f[1];w.width=f[2];w.rows=f[3];w.pitch=f[4];w.mode=f[5];Wc._ASC_FT_Free(e);return w};je.lae=Wc._FT_Load_Glyph;je.gJf=Wc._ASC_FT_Set_Transform;je.mae=Wc._FT_Set_Char_Size;je.Fsf=Wc._ASC_FT_SetCMapForCharCode;je.Lvg=Wc._ASC_FT_GetKerningX;je.Kvg=Wc._ASC_FT_GetFaceMaxAdvanceX;je.D9f=function(e,f,w){e=Wc._ASC_FT_Get_Glyph_Render_Buffer(e);e=new Uint8Array(Wc.HEAP8.buffer,
e,f.pitch*f.rows);if(!w)return e;je.rYb.WH(f.width,f.rows);w=0;var Ia=je.rYb.ZYa.data;if(f.pitch>=f.width)for(var Ra=0;Ra<f.rows;++Ra,w+=f.pitch){var Da=3+Ra*je.rYb.pitch;for(var Ha=0;Ha<f.width;Ha++,Da+=4)Ia[Da]=e[w+Ha]}else{var Sa,Xa;for(Ra=0;Ra<f.rows;++Ra,w+=f.pitch)for(Da=3+Ra*je.rYb.pitch,Ha=Xa=Sa=0;Ha<f.width;Ha++,Da+=4,Sa++)8==Sa&&(Sa=0,Xa++),Ia[Da]=e[w+Xa]&1<<7-Sa?255:0}};je.wEb()})(window,void 0);"use strict";
(function(f,e){function Qa(){this.ld=this.Vw=null;this.B=this.G=this.R=0;this.Lfb=this.hwa=null}function ab(){this.Cua=this.mla=this.GKc=this.X1a=0;this.kT=new Qa}function bb(){this.wia=this.LWa=this.E3a=this.cQa=0;this.b4a=null}function fb(){this.Jnd=this.Lnd=this.Knd=this.FJc=this.Ind=this.Hnd=this.WPb=this.Iib=0}function Da(){this.H6f;this.gba;this.B0f;this.wSc;this.Ana;this.ky=new bb;this.sfa=new fb;this.yEa=!1;this.mz=null}function Ha(){this.qa=this.pa=0;this.Mmb=25.4/72;this.Nmb=25.4/72;this.vCb=
!1;this.ORa=this.jH=this.Enc=this.shift=0}function vb(){this.C_b={};this.TKf=function(f,Da,Ha,Sa,Ra,Ia,Qa){var Gb=f.nv,nb=Ab.ms.IEa(Da);if(e===nb||""==nb)return null;var mb=this.C_b[nb];if(!mb){mb=Ab.XWa[Ab.J$a[nb]];var fb=Ab.J5a.mFa;f.DKf()&&(fb|=Ab.J5a.Eka);f.HKf()&&(fb|=Ab.J5a.Fka);mb=mb.WG(Xa.LR,Gb,f.lEb,fb,f.qEb,f.e2b,e,!0);if(!mb)return null;mb.jPd();this.C_b[nb]=mb}if(!mb)return null;mb.ZRd(f.lEb,f.qEb,f.e2b);f=f.W1b;Gb=mb.W1b;Gb[0]=f[0];Gb[1]=f[1];Gb[2]=f[2];Gb[3]=f[3];Gb[4]=f[4];Gb[5]=f[5];
mb.Nfb();return mb.p_b(Da,Ha,Sa,Ra,Ia,Qa,!0)};this.thb=function(){if(!this.wae){this.wae=!0;for(var e in this.C_b)this.C_b[e].thb();delete this.wae}};this.h3b=function(){if(!this.vae){this.vae=!0;for(var e in this.C_b)this.C_b[e].h3b();delete this.vae}}}var Ab=f.AscFonts,Xa=f.AscCommon;Ab.tZc={F9f:0,WWg:1,Svg:2,YWg:4,Rvg:8,dXg:16,RWg:32,QWg:64,XWg:128,SWg:512,VWg:1024,TWg:2048,UWg:4096,G9f:8192,H9f:32768,OWg:1048576,PWg:2097152,NWg:4194304};Ab.VPd={I9f:0,Zvg:1,$vg:2,Xvg:3,Yvg:4,fXg:5};Ab.eXg={cXg:(Ab.VPd.I9f&
15)<<16,aXg:(Ab.VPd.Zvg&15)<<16,bXg:(Ab.VPd.$vg&15)<<16,ZWg:(Ab.VPd.Xvg&15)<<16,$Wg:(Ab.VPd.Yvg&15)<<16};Ab.QKf=Ab.tZc.F9f|Ab.tZc.Svg|Ab.tZc.G9f|Ab.tZc.H9f;Ab.Ywg=Ab.tZc.F9f|Ab.tZc.G9f|Ab.tZc.H9f;Ab.XPg=function(e){Ab.gjb||(Ab.gjb=[],Ab.gjb.push(4352),Ab.gjb.push(4607),Ab.gjb.push(11904),Ab.gjb.push(40959),Ab.gjb.push(44032),Ab.gjb.push(55215),Ab.gjb.push(63744),Ab.gjb.push(64255),Ab.gjb.push(65280),Ab.gjb.push(65519),Ab.gjb.push(131072),Ab.gjb.push(173791),Ab.gjb.push(194560),Ab.gjb.push(195103));
if(e<Ab.gjb[0])return!1;for(var f=Ab.gjb,Da=Ab.gjb.length,Ha=0;Ha<Da;Ha+=2)if(e>=f[Ha]&&e<=f[Ha+1])return!0;return!1};var mb=Ab.rYb;Ab.rZf=function(){};var Sa=Ab.VPd.I9f,Lb={J1a:0,Epc:1,B1b:2};Qa.prototype={rTf:function(e,f,Da,Ha,Ra){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.Vw?(this.ld.fillStyle=255==this.R&&255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.ld.fillRect(0,0,Ha,Ra)):(e=this.hwa,e.Hya.mPa.fillStyle=255==this.R&&
255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.hwa.Hya.mPa.fillRect(e.wc.Uc*e.Ta,e.wc.qa,Ha,Ra))},sTf:function(e,f,Da,Ha,Ra){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.Vw?(this.ld.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.ld.fillRect(0,0,Ha,Ra)):(e=this.hwa,e.Hya.mPa.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.hwa.Hya.mPa.fillRect(e.wc.Uc*e.Ta,e.wc.qa,Ha,Ra))},iJc:e,se:function(e,f){0!=e&&0!=f&&(this.Vw=
document.createElement("canvas"),this.Vw.width=0==e?1:e,this.Vw.height=0==f?1:f,this.ld=this.Vw.getContext("2d"),this.ld.globalCompositeOperation="source-in")}};Qa.prototype.iJc=Xa.qf.fcb&&Xa.qf.oKc?Qa.prototype.rTf:Qa.prototype.sTf;ab.prototype={rWf:function(e){var f;var Da=!1;Math.max(this.mla,this.Cua)>(null==e.T0a?0:e.T0a.czb)/10&&(Da=!0);var Ha=f=0;Da?(this.kT.se(this.mla,this.Cua),e=this.kT.ld):(this.kT.hwa=e.T0a.hO(this.mla,this.Cua),e=this.kT.hwa.Hya.mPa,f=this.kT.hwa.wc.Uc*this.kT.hwa.Ta,
Ha=this.kT.hwa.wc.qa);0<this.mla&&0<this.Cua&&e.putImageData(mb.ZYa,f,Ha,0,0,this.mla,this.Cua);if(null!=mb.ZYa){var Ra=3;Da=4*(mb.width-this.mla);e=mb.ZYa.data;for(Ha=0;Ha<this.Cua;Ha++){for(f=0;f<this.mla;f++)e[Ra]=0,Ra+=4;Ra+=Da}}},Md:function(e,f,Da){var Ha=this.mla,Ra=this.Cua;if(null!=this.kT.Lfb)e.drawImage(this.kT.Lfb,0,0,Ha,Ra,f,Da,Ha,Ra),this.kT.Lfb=null;else if(null!=this.kT.Vw)e.drawImage(this.kT.Vw,0,0,Ha,Ra,f,Da,Ha,Ra);else{var Ia=this.kT.hwa;e.drawImage(Ia.Hya.uba,Ia.wc.Uc*Ia.Ta,Ia.wc.qa,
Ha,Ra,f,Da,Ha,Ra)}},ryf:function(e,f,Da,Ha,Ra,Ia){if(null!=this.kT.Lfb)e.drawImage(this.kT.Lfb,Ia,0,Ha,Ra,f,Da,Ha,Ra),this.kT.Lfb=null;else if(null!=this.kT.Vw)e.drawImage(this.kT.Vw,Ia,0,Ha,Ra,f,Da,Ha,Ra);else{var Sa=this.kT.hwa;e.drawImage(Sa.Hya.uba,Sa.wc.Uc*Sa.Ta+Ia,Sa.wc.qa,Ha,Ra,f,Da,Ha,Ra)}},syf:function(e,f,Da,Ha){var Ra=f,Ia=Da;f+=this.mla;var Sa=Da+this.Cua,Xa=Da=0,Qa=this.mla,mb=this.Cua;Ra<Ha.ee&&(Da=Ha.ee-Ra,Ra+=Da,Qa-=Da);Ia<Ha.t&&(Xa=Ha.t-Ia,Ia+=Xa,mb-=Xa);f>Ha.r&&(Qa-=f-Ha.r);Sa>Ha.Ya&&
(mb-=Sa-Ha.Ya);0>=Qa||0>=mb||(null!=this.kT.Lfb?(e.drawImage(this.kT.Lfb,Da,Xa,Qa,mb,Ra,Ia,Qa,mb),this.kT.Lfb=null):null!=this.kT.Vw?e.drawImage(this.kT.Vw,Da,Xa,Qa,mb,Ra,Ia,Qa,mb):(Ha=this.kT.hwa,e.drawImage(Ha.Hya.uba,Ha.wc.Uc*Ha.Ta+Da,Ha.wc.qa+Xa,Qa,mb,Ra,Ia,Qa,mb)))},mzb:function(){null!=this.kT.hwa&&this.kT.hwa.Hya.mzb(this.kT.hwa)}};Ha.prototype={start:function(){},Ddg:function(e,f,Da){this.vCb&&(Da.Ex(),this.vCb=!1);this.jH=this.pa+e/64*this.Mmb;this.ORa=this.qa-f/64*this.Nmb;Da.Gj(this.jH,
this.ORa);return 0},v0f:function(e,f){return this.Ddg(e.x,e.y,f)},vdg:function(e,f,Da){this.jH=this.pa+e/64*this.Mmb;this.ORa=this.qa-f/64*this.Nmb;Da.Fc(this.jH,this.ORa);this.vCb=!0;return 0},xCf:function(e,f){return this.vdg(e.x,e.y,f)},Mcg:function(e,f,Da,Ha,Ra){e=this.pa+e/64*this.Mmb;f=this.qa-f/64*this.Nmb;Da=this.pa+Da/64*this.Mmb;Ha=this.qa-Ha/64*this.Nmb;Ra.Zd(1/3*(this.jH+2*e),1/3*(this.ORa+2*f),1/3*(2*e+Da),1/3*(2*f+Ha),Da,Ha);this.jH=Da;this.ORa=Ha;this.vCb=!0;return 0},W1e:function(e,
f,Da){return this.Mcg(e.x,e.y,f.x,f.y,Da)},Pcg:function(e,f,Da,Ha,Ra,Ia,Sa){this.jH=this.pa+Ra/64*this.Mmb;this.ORa=this.qa-Ia/64*this.Nmb;Sa.Zd(this.pa+e/64*this.Mmb,this.qa-f/64*this.Nmb,this.pa+Da/64*this.Mmb,this.qa-Ha/64*this.Nmb,this.jH,this.ORa);this.vCb=!0;return 0},Zxf:function(e,f,Da,Ha){return this.Pcg(e.x,e.y,f.x,f.y,Da.x,Da.y,Ha)},end:function(e){this.vCb&&(e.Ex(),this.vCb=!1)}};f.AscFonts.lzb=Lb;f.AscFonts.JGf=function(){this.N_d="undefined"==typeof Float64Array?Array(6):new Float64Array(6);
this.W1b="undefined"==typeof Float64Array?Array(6):new Float64Array(6);this.J_f=!0;this.SQc=!1;this.lEb=1;this.e2b=this.qEb=0;this.Z5b=this.RQc=!1;this.Kgb=0;this.$1b=new Ab.Arf;this.lMd=0;this.yCa=this.W4=null;this.$df=1;this.Eud=this.Dud=-1;this.yua=!1;this.lla=this.koa=this.hya=this.Iwa=this.P_d=0;this.U1b=[];this.V1b=[];this.nv=null;this.iEb=this.ife=this.Zac=!0;this.Jjg=e;this.Y_b=new vb;this.dJf=function(e,f,Da){Da=Ab.lae(e,f,Da);if(0!=Da&&this.Zac){e=Ab.lae(e,f,Ab.QKf);if(0!=e)return Da;this.Zac=
!1;return e}return Da};this.Bte=function(){var e=this.N_d;this.RQc?(e[0]=1,e[1]=0,e[2]=.3090169943749):(e[0]=1,e[1]=0,e[2]=0);e[3]=1;e[4]=0;e[5]=0;this.Nfb()};this.dMf=function(){var e=this.W1b;e[0]=1;e[1]=0;e[2]=0;e[3]=1;e[4]=0;e[5]=0;this.G7d()};this.G7d=function(){this.iEb=!0;var e=this.W1b;1==e[0]&&0==e[1]&&0==e[2]&&1==e[3]&&(this.iEb=!1,this.Nfb())};this.Nfb=function(){var e=this.N_d,f=this.W1b;Ab.gJf(this.W4,65536*(e[0]*f[0]+e[1]*f[2])>>0,65536*(e[0]*f[1]+e[1]*f[3])>>0,65536*(e[2]*f[0]+e[3]*
f[2])>>0,65536*(e[2]*f[1]+e[3]*f[3])>>0)};this.ZRd=function(e,f,Da){f=f+.5>>0;Da=Da+.5>>0;var Ha=e/this.lEb;if((Ha=1.001<Ha||.999>Ha?!0:!1)||f!=this.qEb||Da!=this.e2b)this.qEb=f,this.e2b=Da,Ha&&(this.lEb=e,this.Nfb()),this.$df=this.qEb/72*this.lEb,this.lMd=Ab.mae(this.W4,0,64*e>>0,f,Da),this.thb()};this.thb=function(){this.r3b();this.h3b();this.Y_b&&this.Y_b.thb()};this.h3b=function(){this.U1b=[];this.V1b=[];this.Y_b&&this.Y_b.h3b()};this.r3b=function(){if(null!=this.nv&&null!=this.nv.T0a){var e=
this.U1b,f;for(f in e)null!=e[f].mz&&e[f].mz.mzb();e=this.V1b;for(f in e)null!=e[f].mz&&e[f].mz.mzb()}};this.Z0a=function(e,f,Da,Ha,Ra,Ia){var Sa=this.W1b,Xa=Sa[0]==e&&Sa[1]==-f&&Sa[2]==-Da&&Sa[3]==Ha;if(Xa&&Sa[4]==Ra&&Sa[5]==Ia)return!1;Sa[0]=e;Sa[1]=-f;Sa[2]=-Da;Sa[3]=Ha;Sa[4]=Ra;Sa[5]=Ia;Xa||this.thb();this.G7d();return!0};this.Rsf=function(e){var f=Ab.Fsf(this.W4,e);if(0<f)return f;-1!=this.Eud&&61440>e&&(f=Ab.Fsf(this.W4,e+61440));return f};this.p_b=function(f,Xa,Qa,nb,Ra,Ia,Gb){var fb=new Da;
fb.H6f=f;var bb=this.yua?f:Ab.Fsf(this.W4,f);0>=bb&&!this.yua&&-1!=this.Eud&&61440>f&&(bb=Ab.Fsf(this.W4,f+61440));if(0>=bb){if(!0===Gb)return null;if(!this.yua&&this.Y_b&&(bb=this.Y_b.TKf(this,f,Xa,Qa,nb,Ra,Ia)))return bb;if(0<=this.Dud)bb=this.Dud,fb.gba=Lb.Epc;else return fb.gba=Lb.B1b,fb.wSc=-1,fb.Ana=(Ab.Kvg(this.W4)>>6)/2,fb}else fb.gba=Lb.J1a;fb.wSc=bb;fb.B0f=0;var Lc=this.DJf();if(this.yua||!Xa||this.Z5b||!Ab.XPg(f))Lc|=Ab.tZc.Rvg;if(this.dJf(this.W4,bb,Lc))return fb;f=null;e!==nb&&(f=new Ha,
f.Mmb=25.4/this.qEb,f.Nmb=25.4/this.e2b,Ra!==e&&(f.pa=Ra),Ia!==e&&(f.qa=Ia));Ra=Ab.Qvg(this.W4,nb,f);if(null==Ra||e!==nb)return fb;nb=65535!=this.yCa.DDf&&800<=this.yCa.jqg?!0:!1;fb.Ana=Ra.NAc*this.$df/this.lla;this.Z5b&&this.nv.qtf&&!nb&&(fb.Ana+=1);fb.ky.cQa=Ra.Qgg>>6;fb.ky.E3a=Ra.Pgg>>6;fb.ky.LWa=Ra.Sgg>>6;fb.ky.wia=Ra.Rgg>>6;Ia=fb.sfa;Ia.Iib=Ra.width>>6;Ia.WPb=Ra.height>>6;Ia.Hnd=Ra.mua>>6;Ia.Ind=Ra.Kqa>>6;Ia.FJc=Ra.ela>>6;Ia.Knd=Ra.dFa>>6;Ia.Lnd=Ra.UDa>>6;Ia.Jnd=Ra.Aka>>6;if(Gb&&0==Ia.FJc&&0==
Ra.width)return null;if(!Xa){if(Qa&&(Xa=Ab.E9f(this.W4,Sa))){nb=Ab.D9f(this.W4,Xa,!1);Xa=fb.ky;f=nb.data;Qa=nb.width;Gb=nb.rows;bb=nb.pitch;nb={uPc:0,vPc:0,oVf:0,nVf:0};Lc=!1;for(Ra=0;Ra<Qa;Ra++){var jc=4*Ra+3;for(Ia=0;Ia<Gb;Ia++,jc+=bb)if(0!=f[jc]){Lc=!0;break}if(Lc)break;nb.uPc++}Lc=!1;for(Ra=Qa-1;0<=Ra;Ra--){jc=4*Ra+3;for(Ia=0;Ia<Gb;Ia++,jc+=bb)if(0!=f[jc]){Lc=!0;break}if(Lc)break;nb.oVf++}Lc=!1;for(Ia=0;Ia<Gb;Ia++){jc=Ia*bb+3;for(Ra=0;Ra<Qa;Ra++,jc+=4)if(0!=f[jc]){Lc=!0;break}if(Lc)break;nb.vPc++}Lc=
!1;for(Ia=Gb-1;0<=Ia;Ia--){jc=Ia*bb+3;for(Ra=0;Ra<Qa;Ra++,jc+=4)if(0!=f[jc]){Lc=!0;break}if(Lc)break;nb.nVf++}if(null!=mb.ZYa)for(f=3,bb=4*(mb.width-Qa),Lc=mb.ZYa.data,Ia=0;Ia<Gb;Ia++){for(Ra=0;Ra<Qa;Ra++)Lc[f]=0,f+=4;f+=bb}Xa.b4a=nb}return fb}fb.yEa=!0;Xa=Ab.E9f(this.W4,Sa);if(!Xa||0==Xa.pitch)return fb;fb.mz=new ab;fb.mz.X1a=Xa.left;fb.mz.GKc=Xa.top;fb.mz.mla=Xa.width;fb.mz.Cua=Xa.rows;Ab.D9f(this.W4,Xa,!0);if(this.Z5b&&this.J_f&&!nb)for(fb.mz.mla++,Xa=fb.mz.mla,Qa=fb.mz.Cua,Ia=mb.ZYa.data,Ra=Gb=
0;Gb<Qa;++Gb,Ra+=mb.pitch)for(nb=Xa-1;0<=nb;--nb)0!=nb&&(f=Ra+4*nb+3,Ia[f]=Xa-1==nb?Ia[f-4]:Math.min(255,Ia[f-4]+Ia[f]));fb.mz.rWf(this.nv);return fb};this.Qaa=function(f){if(0>=f.fH)return!0;var Da=0,Ha=0;this.iEb&&this.Nfb();for(var Sa=!1===this.yua?this.U1b:this.V1b,Ra=0;Ra<f.fH;++Ra){var Ia=f.nHb(Ra).GOa,Xa=Sa[Ia];e==Xa&&(Sa[Ia]=this.p_b(Ia,!1),Xa=Sa[Ia]);Ia=Xa.wSc;var Qa=Xa.gba;Lb.B1b==Qa?(f.dIc(Ra,Ha,0),f.YHc(Ra,0,0,0,0),f.SKb(Ra,Lb.B1b),Ha+=Xa.Ana+this.Kgb,Da=0):(Lb.Epc==Qa?f.SKb(Ra,Lb.Epc):
f.SKb(Ra,Lb.J1a),this.SQc&&Da&&0<Ra&&f.nHb(Ra).gba==f.nHb(Ra-1).gba&&(Ha+=this.kac(Da,Ia)),Da=f.XY+Ha,Qa=f.YY+0,f.dIc(Ra,f.pfa[4]+Da*f.pfa[0]+Qa*f.pfa[2]-f.XY,f.pfa[5]+Da*f.pfa[1]+Qa*f.pfa[3]-f.YY),Da=Xa.sfa,f.tuf(Ra,Da.Iib,Da.WPb,Da.FJc,Da.Hnd,Da.Ind,Da.Jnd,Da.Knd,Da.Lnd),f.YHc(Ra,Xa.ky.cQa,Xa.ky.wia,Xa.ky.E3a,Xa.ky.LWa),Ha+=Xa.Ana+this.Kgb,Da=Ia)}f.Wvb=Ha+f.XY;f.PWb=0+f.YY};this.ic=function(f){if(0>=f.fH)return!0;this.iEb&&this.Nfb();for(var Da=0,Ha=0,Sa=!1===this.yua?this.U1b:this.V1b,Ra=0;Ra<
f.fH;++Ra){var Ia=f.nHb(Ra),Xa=Ia.GOa,Qa=Sa[Xa];if(e==Qa||null==Qa.mz)Sa[Xa]=this.p_b(Xa,!0),Qa=Sa[Xa];Xa=Qa.wSc;var mb=Qa.gba;Lb.B1b==mb?(f.dIc(Ra,Ha,0),f.YHc(Ra,0,0,0,0),f.SKb(Ra,Lb.B1b),Ha+=Qa.Ana+this.Kgb,Da=0):(Lb.Epc==mb?f.SKb(Ra,Lb.Epc):f.SKb(Ra,Lb.J1a),this.SQc&&Da&&0<Ra&&f.nHb(Ra).gba==f.nHb(Ra-1).gba&&(Ha+=this.kac(Da,Xa)),Da=f.XY+Ha,mb=f.YY+0,f.dIc(Ra,f.pfa[4]+Da*f.pfa[0]+mb*f.pfa[2]-f.XY,f.pfa[5]+Da*f.pfa[1]+mb*f.pfa[3]-f.YY),Ia.sfa=Qa.sfa,f.YHc(Ra,Qa.ky.cQa,Qa.ky.wia,Qa.ky.E3a,Qa.ky.LWa),
Ha+=Qa.Ana+this.Kgb,Ia.yEa=Qa.yEa,Ia.mz=Qa.mz,Da=Xa)}f.Wvb=Ha+f.XY;f.PWb=0+f.YY};this.eFd=function(f){this.iEb&&this.Nfb();var Da=f.XK[0],Ha=Da.GOa,Sa=!1===this.yua?this.U1b:this.V1b,Ra=Sa[Ha];if(e==Ra||null==Ra.mz&&!1===Ra.yEa)Sa[Ha]=this.p_b(Ha,!0),Ra=Sa[Ha];if(Ra)if(Ha=Ra.gba,Da.gba=Ra.gba,Lb.B1b==Ha)Da.Xy=0,Da.Yx=0,Da.aGa=0,Da.Rxa=0,Da.dQa=0,Da.$Fa=0;else{Ha=f.XY;Sa=f.YY;var Ia=f.pfa;Da.Xy=Ia[4]+Ha*Ia[0]+Sa*Ia[2]-f.XY;Da.Yx=Ia[5]+Ha*Ia[1]+Sa*Ia[3]-f.YY;Da.sfa=Ra.sfa;Da.yEa=Ra.yEa;Da.mz=Ra.mz;
f.Wvb=Ra.Ana+this.Kgb+f.XY;f.PWb=f.YY}};this.s_=function(f,Da){this.iEb&&this.Nfb();var Ha=!1===this.yua?this.U1b:this.V1b,Sa=Ha[f];e==Sa&&(Ha[f]=this.p_b(f,!1,Da),Sa=Ha[f]);return Sa};this.EJf=function(e,f,Da,Ha){this.iEb&&this.Nfb();this.p_b(e,!1,!1,f,Da,Ha)};this.Usf=function(e,f){var Da=e.fH;if(!(0>=Da))for(var Ha=0;Ha<Da;++Ha){var Ra=e.XK[Ha],Ia=e.XY+25.4*Ra.Xy/this.qEb,Sa=e.YY+25.4*Ra.Yx/this.e2b;f.xj();this.EJf(Ra.GOa,f,Ia,Sa);f.et();f.Yt()}};this.DJf=function(){return this.Zac&&this.ife?this.nv.YQd:
Ab.QKf};this.kac=function(e,f){return Ab.Lvg(this.W4,e,f)>>6};this.jEa=function(e){this.yua!=e&&(this.yua=e)};this.ruf=function(e){this.Kgb=e};this.DKf=function(){return this.Z5b?!0:-1!=this.yCa.KDa.indexOf("Bold")?!0:!1};this.HKf=function(){return this.RQc?!0:-1!=this.yCa.KDa.indexOf("Italic")?!0:!1};this.vuf=function(e){this.RQc!=e&&(this.thb(),this.RQc=e,this.Bte())};this.uuf=function(e){this.Z5b!=e&&(this.thb(),this.Z5b=e)};this.SQd=function(){return 0==this.lMd};this.Q5a=function(){return this.Iwa};
this.iSa=function(){return this.hya};this.UG=function(){return this.koa};this.jPd=function(){this.ife=this.Zac=!0};this.Ghg=function(){var e=this.yCa,f=[];f.push(e.MQa);65535!=e.DDf?(f.push(e.a1f),f.push(-e.b1f)):(f.push(e.Clg),f.push(e.Dlg));return f};this.uyg=function(e,f){this.W4=e;this.yCa=new Ab.hug;this.yCa.load(this.W4);this.lla=this.yCa.MQa;this.Iwa=this.yCa.z5;this.hya=this.yCa.zZ;this.koa=this.yCa.height;if(f.vtf&&65535!=this.yCa.DDf)if(f.nFd){var Da=this.yCa.a1f,Ha=-this.yCa.b1f;if(0!=
(this.yCa.hqg&770703360)){var Ra=.3*(Da-Ha)>>0;Da+=Ra+1>>1;Ha-=Ra>>1}this.yCa.height<Da-Ha&&(this.Iwa=Da,this.hya=Ha,this.koa=Da-Ha)}else 128==(this.yCa.eqg&128)&&(this.Iwa=this.yCa.Z0f,this.hya=this.yCa.$0f,this.koa=this.yCa.Z0f-this.yCa.$0f+this.yCa.gqg);this.P_d=this.yCa.n2b;this.Dud=this.yCa.iqg;this.Eud=this.yCa.fqg;this.lMd=Ab.mae(e,0,64*this.lEb,0,0);this.dMf();this.Bte();!0===f.SQc&&(this.SQc=0!=(this.yCa.VZ&64)?!0:!1);if(0!=this.yCa.XCf.length)for(this.Jjg=[],e=this.yCa.XCf.length-1;0<=e;e--)this.Jjg[this.yCa.XCf[e]>>
6]=!0}};f.AscFonts.wEb()})(window);"use strict";(function(f){function e(){this.lL=Qa.cvg();this.ACa=null;this.CDf=function(e,f){e=Qa.fJf(this.lL,e,f);if(!e)return null;f=new Qa.JGf;f.uyg(e,this.ACa);return f.SQd()?f:null};this.o1d=function(e,f){f=e&&f?Qa.Ryg:Qa.Qyg;this.ACa.YQd=e?Qa.Ywg:Qa.QKf;Qa.awg(this.lL,f)}}var Qa=f.AscFonts;f.AscFonts.zyf=function(f){var bb=new e;bb.ACa=f;bb.o1d(f.kId,f.lId);f.Pzb=bb;Qa.rZf()};f.AscFonts.DMg=function(){};f.AscFonts.wEb()})(window);
