/*
 * Copyright (C) Ascensio System SIA 2012-2020. All rights reserved
 *
 * https://www.onlyoffice.com/
 *
 * Version: 0.0.0 (build:0)
 */

(function(f,e){function Pa(e){return Wc.locateFile?Wc.locateFile(e,af):af+e}function ab(e){var f=be[ge>>2];e=f+e+15&-16;if(e<=ae)be[ge>>2]=e;else if(!Nc(e))return 0;return f}function bb(e,f,w){var Oa=f+w;for(w=f;e[w]&&!(w>=Oa);)++w;if(16<w-f&&e.subarray&&Ce)return Ce.decode(e.subarray(f,w));for(Oa="";f<w;){var Ia=e[f++];if(Ia&128){var Ra=e[f++]&63;if(192==(Ia&224))Oa+=String.fromCharCode((Ia&31)<<6|Ra);else{var Da=e[f++]&63;Ia=224==(Ia&240)?(Ia&15)<<12|Ra<<6|Da:(Ia&7)<<18|Ra<<12|Da<<6|e[f++]&63;65536>
Ia?Oa+=String.fromCharCode(Ia):(Ia-=65536,Oa+=String.fromCharCode(55296|Ia>>10,56320|Ia&1023))}}else Oa+=String.fromCharCode(Ia)}return Oa}function nb(e,f){0<e%f&&(e+=f-e%f);return e}function Da(){Wc.HEAP8=he=new Int8Array(ch);Wc.HEAP16=new Int16Array(ch);Wc.HEAP32=be=new Int32Array(ch);Wc.HEAPU8=De=new Uint8Array(ch);Wc.HEAPU16=new Uint16Array(ch);Wc.HEAPU32=new Uint32Array(ch);Wc.HEAPF32=new Float32Array(ch);Wc.HEAPF64=new Float64Array(ch)}function Ha(f){for(;0<f.length;){var w=f.shift();if("function"==
typeof w)w();else{var Oa=w.func;"number"===typeof Oa?w.wQf===e?Wc.dynCall_v(Oa):Wc.dynCall_vi(Oa,w.wQf):Oa(w.wQf===e?null:w.wQf)}}}function Eb(e){return String.prototype.startsWith?e.startsWith("data:application/octet-stream;base64,"):0===e.indexOf("data:application/octet-stream;base64,")}function zb(){try{if(Wc.wasmBinary)return new Uint8Array(Wc.wasmBinary);if(Wc.readBinary)return Wc.readBinary(Oe);throw"both async and sync fetching of the wasm failed";}catch(Oa){Ra(Oa)}}function Va(){return Wc.wasmBinary||
!eg&&!Ye||"function"!==typeof ie?new Promise(function(e){e(zb())}):ie(Oe,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+Oe+"'";return e.arrayBuffer()}).catch(function(){return zb()})}function gb(e){function f(e){Wc.asm=e.exports;Eg--;Wc.monitorRunDependencies&&Wc.monitorRunDependencies(Eg);0==Eg&&(null!==sd&&(clearInterval(sd),sd=null),Hf&&(e=Hf,Hf=null,e()))}function w(e){f(e.instance)}function Oa(e){xf().then(function(e){return WebAssembly.instantiate(e,
Ia)}).then(e,function(e){sh("failed to asynchronously prepare wasm: "+e);Ra(e)})}var Ia={env:e,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:Mf};Eg++;Wc.monitorRunDependencies&&Wc.monitorRunDependencies(Eg);if(Wc.instantiateWasm)try{return Wc.instantiateWasm(Ia,f)}catch(Bj){return sh("Module.instantiateWasm callback failed with error: "+Bj),!1}Wc.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Eb(Oe)||"function"!==typeof ie?Oa(w):WebAssembly.instantiateStreaming(ie(Oe,
{credentials:"same-origin"}),Ia).then(w,function(e){sh("wasm streaming compile failed: "+e);sh("falling back to ArrayBuffer instantiation");Oa(w)});return{}}function Za(e){if(Za.yKg){var f=be[e>>2];var w=be[f>>2]}else Za.yKg=!0,Ee.USER=Ee.LOGNAME="web_user",Ee.PATH="/",Ee.PWD="/",Ee.HOME="/home/web_user",Ee.LANG="C.UTF-8",Ee._=Wc.thisProgram,w=yc?ad(1024):ab(1024),f=yc?ad(256):ab(256),be[f>>2]=w,be[e>>2]=f;e=[];var Oa=0,Ia;for(Ia in Ee)if("string"===typeof Ee[Ia]){var Ra=Ia+"="+Ee[Ia];e.push(Ra);
Oa+=Ra.length}if(1024<Oa)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(Ia=0;Ia<e.length;Ia++){Oa=Ra=e[Ia];for(var Da=w,Ha=0;Ha<Oa.length;++Ha)he[Da++>>0]=Oa.charCodeAt(Ha);he[Da>>0]=0;be[f+4*Ia>>2]=w;w+=Ra.length+1}be[f+4*e.length>>2]=0}function bc(e,f){uc(e,f||1);throw"longjmp";}function Nc(e){if(2147418112<e)return!1;for(var f=Math.max(ae,16777216);f<e;)f=536870912>=f?nb(2*f,65536):Math.min(nb((3*f+2147483648)/4,65536),2147418112);e=nb(f,65536);var w=Wc.buffer.byteLength;try{var Oa=
-1!==Td.grow((e-w)/65536)?Wc.buffer=Td.buffer:null}catch(Ak){Oa=null}if(!Oa||Oa.byteLength!=f)return!1;Wc.buffer=ch=Oa;Da();ae=f;return!0}function cc(e){if(0===e)return 0;e=e?bb(De,e,void 0):"";if(!Ee.hasOwnProperty(e))return 0;cc.Z2f&&Ke(cc.Z2f);e=Ee[e];for(var f=0,w=0;w<e.length;++w){var Oa=e.charCodeAt(w);55296<=Oa&&57343>=Oa&&(Oa=65536+((Oa&1023)<<10)|e.charCodeAt(++w)&1023);127>=Oa?++f:f=2047>=Oa?f+2:65535>=Oa?f+3:f+4}var Ia=f+1;if(f=ad(Ia))if(w=he,Oa=f,0<Ia){Ia=Oa+Ia-1;for(var Ra=0;Ra<e.length;++Ra){var Da=
e.charCodeAt(Ra);if(55296<=Da&&57343>=Da){var Ha=e.charCodeAt(++Ra);Da=65536+((Da&1023)<<10)|Ha&1023}if(127>=Da){if(Oa>=Ia)break;w[Oa++]=Da}else{if(2047>=Da){if(Oa+1>=Ia)break;w[Oa++]=192|Da>>6}else{if(65535>=Da){if(Oa+2>=Ia)break;w[Oa++]=224|Da>>12}else{if(Oa+3>=Ia)break;w[Oa++]=240|Da>>18;w[Oa++]=128|Da>>12&63}w[Oa++]=128|Da>>6&63}w[Oa++]=128|Da&63}}w[Oa]=0}cc.Z2f=f;return cc.Z2f}function Rb(e){this.name="ExitStatus";this.message="Program terminated with exit("+e+")";this.status=e}function ob(){function e(){if(!Wc.calledRun&&
(Wc.calledRun=!0,!xc)){yc||(yc=!0,Ha(vh));Ha(Yg);if(Wc.onRuntimeInitialized)Wc.onRuntimeInitialized();if(Wc.postRun)for("function"==typeof Wc.postRun&&(Wc.postRun=[Wc.postRun]);Wc.postRun.length;)$b.unshift(Wc.postRun.shift());Ha($b)}}if(!(0<Eg)){if(Wc.preRun)for("function"==typeof Wc.preRun&&(Wc.preRun=[Wc.preRun]);Wc.preRun.length;)Cc.unshift(Wc.preRun.shift());Ha(Cc);0<Eg||Wc.calledRun||(Wc.setStatus?(Wc.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Wc.setStatus("")},1);e()},
1)):e())}}function Ra(f){if(Wc.onAbort)Wc.onAbort(f);f!==e?(Qf(f),sh(f),f=JSON.stringify(f)):f="";xc=!0;throw"abort("+f+"). Build with -s ASSERTIONS=1 for more info.";}function Ia(){this.lVd=this.yLc=this.p2b=this.mL=this.iCc=this.VZ=this.height=this.zZ=this.z5=this.MQa=0;this.KDa=this.N4="";this.Dlg=this.Elg=this.gqg=this.iqg=this.hqg=this.a1f=this.$0f=this.jqg=this.c1f=this.b1f=this.fqg=this.kqg=this.EDf=0;this.YCf=[]}function Ab(){this.zKc=this.RAc=this.UDa=this.dFa=this.Aka=this.Kqa=this.mua=
this.ela=this.height=this.width=this.Sgg=this.Qgg=this.Tgg=this.Rgg=0}function $d(){this.mode=this.pitch=this.rows=this.width=this.top=this.left=0}var re=f.AscFonts,ie=f.fetch,xf=null;f.AscDesktopEditor&&document.currentScript&&0==document.currentScript.src.indexOf("file:///")?(ie=e,xf=function(){var e="ascdesktop://fonts/"+Oe.substr(8);return new Promise(function(f){var w=new XMLHttpRequest;w.open("GET",e,!0);w.responseType="arraybuffer";w.overrideMimeType?w.overrideMimeType("text/plain; charset=x-user-defined"):
w.setRequestHeader("Accept-Charset","x-user-defined");w.onload=function(){200==this.status&&f(new Uint8Array(this.response))};w.send(null)})}):xf=function(){return Va()};var Wc="undefined"!==typeof Wc?Wc:{},Pi={},Jd;for(Jd in Wc)Wc.hasOwnProperty(Jd)&&(Pi[Jd]=Wc[Jd]);Wc.arguments=[];Wc.thisProgram="./this.program";Wc.quit=function(e,f){throw f;};Wc.preRun=[];Wc.postRun=[];var eg=!0,Ye=!1,af="";if(eg||Ye)Ye?af=self.location.href:document.currentScript&&(af=document.currentScript.src),af=0!==af.indexOf("blob:")?
af.substr(0,af.lastIndexOf("/")+1):"",Wc.read=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.send(null);return f.responseText},Ye&&(Wc.readBinary=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.responseType="arraybuffer";f.send(null);return new Uint8Array(f.response)}),Wc.readAsync=function(e,f,w){var Oa=new XMLHttpRequest;Oa.open("GET",e,!0);Oa.responseType="arraybuffer";Oa.onload=function(){200==Oa.status||0==Oa.status&&Oa.response?f(Oa.response):w()};Oa.onerror=w;Oa.send(null)},
Wc.setWindowTitle=function(e){document.title=e};var Qf=Wc.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof e?e:null),sh=Wc.printErr||("undefined"!==typeof e?e:"undefined"!==typeof console&&console.warn.bind(console)||Qf);for(Jd in Pi)Pi.hasOwnProperty(Jd)&&(Wc[Jd]=Pi[Jd]);Pi=e;var Mf={"f64-rem":function(e,f){return e%f},"debugger":function(){debugger}},sb=0;"object"!==typeof WebAssembly&&sh("no native wasm support detected");var xc=!1,Ce="undefined"!==typeof TextDecoder?
new TextDecoder("utf8"):e;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var he,De,be,ge=109360,ae=Wc.TOTAL_MEMORY||16777216;5242880>ae&&sh("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ae+"! (TOTAL_STACK=5242880)");if(Wc.buffer)var ch=Wc.buffer;else{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory){var Td=new WebAssembly.Memory({initial:ae/65536});ch=Td.buffer}else ch=new ArrayBuffer(ae);Wc.buffer=ch}Da();be[ge>>2]=5352496;var Cc=[],vh=[],Yg=[],$b=
[function(){f.AscFonts.yEb()}],yc=!1,Eg=0,sd=null,Hf=null;Wc.preloadedImages={};Wc.preloadedAudios={};var Oe="fonts.wasm";Eb(Oe)||(Oe=Pa(Oe));Wc.asm=function(e,f){f.memory=Td;f.table=new WebAssembly.Table({initial:814,maximum:814,element:"anyfunc"});f.__memory_base=1024;f.__table_base=0;return gb(f)};vh.push({func:function(){zd()}});var Ee={},Xb={SPa:[null,[],[]],GRg:function(e,f){var w=Xb.SPa[e];0===f||10===f?((1===e?Qf:sh)(bb(w,0)),w.length=0):w.push(f)},MLc:0,get:function(){Xb.MLc+=4;return be[Xb.MLc-
4>>2]},E1a:function(){var e=Xb.get();return e?bb(De,e,void 0):""},lZg:function(){var e=Xb.get();Xb.get();return e},qZg:function(){Xb.get()}};Pi=Wc.asm({},{b:Ra,e:function(e){sb=e},d:function(){return sb},r:function(e,f,w){var Oa=Fg();try{return Nn(e,f,w)}catch(Ak){Be(Oa);if(Ak!==Ak+0&&"longjmp"!==Ak)throw Ak;uc(1,0)}},q:function(e,f,w,Ia){var Oa=Fg();try{return dj(e,f,w,Ia)}catch(Bj){Be(Oa);if(Bj!==Bj+0&&"longjmp"!==Bj)throw Bj;uc(1,0)}},p:function(e,f,w,Ia,Ra){var Oa=Fg();try{return Qi(e,f,w,Ia,
Ra)}catch(Oo){Be(Oa);if(Oo!==Oo+0&&"longjmp"!==Oo)throw Oo;uc(1,0)}},o:function(e,f,w){var Oa=Fg();try{Uj(e,f,w)}catch(Ak){Be(Oa);if(Ak!==Ak+0&&"longjmp"!==Ak)throw Ak;uc(1,0)}},n:function(e,f,Ia,Ra,Da){var Oa=Fg();try{w(e,f,Ia,Ra,Da)}catch(Oo){Be(Oa);if(Oo!==Oo+0&&"longjmp"!==Oo)throw Oo;uc(1,0)}},m:Za,l:function(){},k:function(e){Wc.___errno_location&&(be[Wc.___errno_location()>>2]=e);return e},A:function(f,w){Xb.MLc=w;try{var Oa=Xb.Ykg();Xb.get();var Ia=Xb.get(),Da=Xb.get(),Ha=Xb.get();e.GZg(Oa,
Ia,Ha);be[Da>>2]=Oa.position;Oa.kPg&&0===Ia&&0===Ha&&(Oa.kPg=null);return 0}catch(Oo){return"undefined"!==typeof e&&Oo instanceof e.Csf||Ra(Oo),-Oo.Cyf}},z:function(f,w){Xb.MLc=w;try{var Oa=Xb.Ykg(),Ia=Xb.get(),Da=Xb.get();return Xb.aZg(Oa,Ia,Da)}catch(Bj){return"undefined"!==typeof e&&Bj instanceof e.Csf||Ra(Bj),-Bj.Cyf}},j:function(f,w){Xb.MLc=w;try{var Oa=Xb.get(),Ia=Xb.get(),Da=Xb.get();for(w=f=0;w<Da;w++){for(var Ha=be[Ia+8*w>>2],Za=be[Ia+(8*w+4)>>2],Va=0;Va<Za;Va++)Xb.GRg(Oa,De[Ha+Va]);f+=Za}return f}catch(Ri){return"undefined"!==
typeof e&&Ri instanceof e.Csf||Ra(Ri),-Ri.Cyf}},f:function(e,f){Xb.MLc=f;return 0},y:function(f,w){Xb.MLc=w;try{var Oa=Xb.E1a(),Ia=Xb.get(),Da=Xb.get();return e.open(Oa,Ia,Da).fZg}catch(Bj){return"undefined"!==typeof e&&Bj instanceof e.Csf||Ra(Bj),-Bj.Cyf}},i:function(e,f){Xb.MLc=f;return 0},h:function(f,w){Xb.MLc=w;try{var Oa=Xb.Ykg();e.close(Oa);return 0}catch(rm){return"undefined"!==typeof e&&rm instanceof e.Csf||Ra(rm),-rm.Cyf}},g:function(){},x:function(){return ae},w:function(e,f){bc(e,f)},
v:function(e,f,w){De.set(De.subarray(f,f+w),e)},u:Nc,t:cc,c:bc,s:function(){Ra("OOM")},a:ge},ch);Wc.asm=Pi;Wc._ASC_FT_Free=function(){return Wc.asm.B.apply(null,arguments)};Wc._ASC_FT_GetFaceInfo=function(){return Wc.asm.C.apply(null,arguments)};Wc._ASC_FT_GetFaceMaxAdvanceX=function(){return Wc.asm.D.apply(null,arguments)};Wc._ASC_FT_GetKerningX=function(){return Wc.asm.E.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Measure_Params=function(){return Wc.asm.F.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Render_Buffer=
function(){return Wc.asm.G.apply(null,arguments)};Wc._ASC_FT_Get_Glyph_Render_Params=function(){return Wc.asm.H.apply(null,arguments)};Wc._ASC_FT_Glyph_Get_CBox=function(){return Wc.asm.I.apply(null,arguments)};Wc._ASC_FT_Init=function(){return Wc.asm.J.apply(null,arguments)};Wc._ASC_FT_Malloc=function(){return Wc.asm.K.apply(null,arguments)};Wc._ASC_FT_Open_Face=function(){return Wc.asm.L.apply(null,arguments)};Wc._ASC_FT_SetCMapForCharCode=function(){return Wc.asm.M.apply(null,arguments)};Wc._ASC_FT_Set_Transform=
function(){return Wc.asm.N.apply(null,arguments)};Wc._ASC_FT_Set_TrueType_HintProp=function(){return Wc.asm.O.apply(null,arguments)};Wc._FT_Done_Face=function(){return Wc.asm.P.apply(null,arguments)};Wc._FT_Done_FreeType=function(){return Wc.asm.Q.apply(null,arguments)};Wc._FT_Get_Glyph=function(){return Wc.asm.R.apply(null,arguments)};Wc._FT_Load_Glyph=function(){return Wc.asm.S.apply(null,arguments)};Wc._FT_Set_Char_Size=function(){return Wc.asm.T.apply(null,arguments)};Wc._FT_Set_Transform=function(){return Wc.asm.U.apply(null,
arguments)};var zd=Wc.___emscripten_environ_constructor=function(){return Wc.asm.V.apply(null,arguments)},Ke=Wc._free=function(){return Wc.asm.W.apply(null,arguments)},ad=Wc._malloc=function(){return Wc.asm.X.apply(null,arguments)},uc=Wc._setThrew=function(){return Wc.asm.Y.apply(null,arguments)},Be=Wc.stackRestore=function(){return Wc.asm.da.apply(null,arguments)},Fg=Wc.stackSave=function(){return Wc.asm.ea.apply(null,arguments)},Nn=Wc.dynCall_iii=function(){return Wc.asm.Z.apply(null,arguments)},
dj=Wc.dynCall_iiii=function(){return Wc.asm._.apply(null,arguments)},Qi=Wc.dynCall_iiiii=function(){return Wc.asm.$.apply(null,arguments)};Wc.dynCall_vi=function(){return Wc.asm.aa.apply(null,arguments)};var Uj=Wc.dynCall_vii=function(){return Wc.asm.ba.apply(null,arguments)},w=Wc.dynCall_viiii=function(){return Wc.asm.ca.apply(null,arguments)};Wc.asm=Pi;Rb.prototype=Error();Rb.prototype.constructor=Rb;Hf=function Km(){Wc.calledRun||ob();Wc.calledRun||(Hf=Km)};Wc.run=ob;Wc.abort=Ra;if(Wc.preInit)for("function"==
typeof Wc.preInit&&(Wc.preInit=[Wc.preInit]);0<Wc.preInit.length;)Wc.preInit.pop()();Wc.noExitRuntime=!0;ob();f.AscFonts=f.AscFonts||{};re=f.AscFonts;re.dvg=function(){return Wc._ASC_FT_Init()};re.Ryg=35;re.aYg=38;re.Syg=40;re.bwg=function(e,f){Wc._ASC_FT_Set_TrueType_HintProp(e,f)};re.evg=function(e){var f=Wc._ASC_FT_Malloc(e.size);Wc.HEAP8.set(e.data,f);return{MHg:!0,data:f,li:e.size}};re.CPd=function(e){var f=re.o5b[e];f&&!0!==f.MHg&&(f=re.evg(re.o5b[e]),re.o5b[e]=null,re.o5b[e]=f)};Ia.prototype.load=
function(e){if(e=Wc._ASC_FT_GetFaceInfo(e)){var f=new Int32Array(Wc.HEAP8.buffer,e,Math.min(Wc.HEAP8.length-e>>2,250)),w=0;this.MQa=Math.abs(f[w++]);this.z5=f[w++];this.zZ=f[w++];this.height=f[w++];this.VZ=f[w++];this.iCc=f[w++];this.mL=f[w++];this.p2b=f[w++];this.yLc=f[w++];this.lVd=f[w++];for(var Ia=f[w++];Ia;)this.N4+=String.fromCharCode(Ia),Ia=f[w++];for(Ia=f[w++];Ia;)this.KDa+=String.fromCharCode(Ia),Ia=f[w++];this.EDf=f[w++];this.kqg=f[w++];this.fqg=f[w++];this.b1f=f[w++];this.c1f=f[w++];this.jqg=
f[w++];this.$0f=f[w++];this.a1f=f[w++];this.hqg=f[w++];w++;this.iqg=re.dU.aQ(f[w++]);w++;w++;w++;w++;this.gqg=f[w++];this.Elg=f[w++];this.Dlg=f[w++];Ia=f[w++];for(var Ra=0;Ra<Ia;Ra++)this.YCf.push(f[w++]);Wc._ASC_FT_Free(e)}};re.iug=Ia;re.tWg=Ab;re.sWg=$d;re.gJf=function(e,f,w){return Wc._ASC_FT_Open_Face(e,f.data,f.li,w)};re.Rvg=function(e,f,w){e=Wc._ASC_FT_Get_Glyph_Measure_Params(e,f?1:0);if(!e)return null;var Ia=15;f&&(Ia=Wc.HEAP32[e>>2]);var Ra=new Int32Array(Wc.HEAP8.buffer,e,4*Ia),Da=new Ab;
Da.Rgg=Ra[1];Da.Tgg=Ra[2];Da.Qgg=Ra[3];Da.Sgg=Ra[4];Da.width=Ra[5];Da.height=Ra[6];Da.ela=Ra[7];Da.mua=Ra[8];Da.Kqa=Ra[9];Da.Aka=Ra[10];Da.dFa=Ra[11];Da.UDa=Ra[12];Da.RAc=Ra[13];Da.zKc=Ra[14];if(f){w.start(f);for(var Ha=15;Ha<Ia;)switch(Ra[Ha++]){case 0:w.Edg(Ra[Ha++],Ra[Ha++],f);break;case 1:w.wdg(Ra[Ha++],Ra[Ha++],f);break;case 2:w.Ncg(Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],f);break;case 3:w.Qcg(Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],Ra[Ha++],f)}w.end(f)}Wc._ASC_FT_Free(e);return Da};re.F9f=
function(e,f){e=Wc._ASC_FT_Get_Glyph_Render_Params(e,f);if(!e)return null;f=new Int32Array(Wc.HEAP8.buffer,e,24);var w=new $d;w.left=f[0];w.top=f[1];w.width=f[2];w.rows=f[3];w.pitch=f[4];w.mode=f[5];Wc._ASC_FT_Free(e);return w};re.oae=Wc._FT_Load_Glyph;re.hJf=Wc._ASC_FT_Set_Transform;re.pae=Wc._FT_Set_Char_Size;re.Gsf=Wc._ASC_FT_SetCMapForCharCode;re.Mvg=Wc._ASC_FT_GetKerningX;re.Lvg=Wc._ASC_FT_GetFaceMaxAdvanceX;re.E9f=function(e,f,w){e=Wc._ASC_FT_Get_Glyph_Render_Buffer(e);e=new Uint8Array(Wc.HEAP8.buffer,
e,f.pitch*f.rows);if(!w)return e;re.tYb.WH(f.width,f.rows);w=0;var Ia=re.tYb.ZYa.data;if(f.pitch>=f.width)for(var Ra=0;Ra<f.rows;++Ra,w+=f.pitch){var Da=3+Ra*re.tYb.pitch;for(var Ha=0;Ha<f.width;Ha++,Da+=4)Ia[Da]=e[w+Ha]}else{var Za,Va;for(Ra=0;Ra<f.rows;++Ra,w+=f.pitch)for(Da=3+Ra*re.tYb.pitch,Ha=Va=Za=0;Ha<f.width;Ha++,Da+=4,Za++)8==Za&&(Za=0,Va++),Ia[Da]=e[w+Va]&1<<7-Za?255:0}};re.yEb()})(window,void 0);"use strict";
(function(f,e){function Pa(){this.ld=this.Vw=null;this.B=this.G=this.R=0;this.Nfb=this.hwa=null}function ab(){this.Cua=this.mla=this.KKc=this.X1a=0;this.kT=new Pa}function bb(){this.wia=this.LWa=this.E3a=this.cQa=0;this.b4a=null}function nb(){this.Nnd=this.Pnd=this.Ond=this.JJc=this.Mnd=this.Lnd=this.YPb=this.Kib=0}function Da(){this.I6f;this.gba;this.C0f;this.ASc;this.Ana;this.ky=new bb;this.sfa=new nb;this.yEa=!1;this.mz=null}function Ha(){this.qa=this.pa=0;this.Omb=25.4/72;this.Pmb=25.4/72;this.xCb=
!1;this.ORa=this.jH=this.Inc=this.shift=0}function Eb(){this.E_b={};this.UKf=function(f,Da,Ha,Za,Ra,Ia,Pa){var Ab=f.nv,ob=zb.ms.IEa(Da);if(e===ob||""==ob)return null;var gb=this.E_b[ob];if(!gb){gb=zb.XWa[zb.J$a[ob]];var nb=zb.J5a.mFa;f.EKf()&&(nb|=zb.J5a.Eka);f.IKf()&&(nb|=zb.J5a.Fka);gb=gb.WG(Va.LR,Ab,f.nEb,nb,f.sEb,f.g2b,e,!0);if(!gb)return null;gb.mPd();this.E_b[ob]=gb}if(!gb)return null;gb.bSd(f.nEb,f.sEb,f.g2b);f=f.Y1b;Ab=gb.Y1b;Ab[0]=f[0];Ab[1]=f[1];Ab[2]=f[2];Ab[3]=f[3];Ab[4]=f[4];Ab[5]=f[5];
gb.Pfb();return gb.r_b(Da,Ha,Za,Ra,Ia,Pa,!0)};this.vhb=function(){if(!this.zae){this.zae=!0;for(var e in this.E_b)this.E_b[e].vhb();delete this.zae}};this.j3b=function(){if(!this.yae){this.yae=!0;for(var e in this.E_b)this.E_b[e].j3b();delete this.yae}}}var zb=f.AscFonts,Va=f.AscCommon;zb.xZc={G9f:0,XWg:1,Tvg:2,ZWg:4,Svg:8,eXg:16,SWg:32,RWg:64,YWg:128,TWg:512,WWg:1024,UWg:2048,VWg:4096,H9f:8192,I9f:32768,PWg:1048576,QWg:2097152,OWg:4194304};zb.YPd={J9f:0,$vg:1,awg:2,Yvg:3,Zvg:4,gXg:5};zb.fXg={dXg:(zb.YPd.J9f&
15)<<16,bXg:(zb.YPd.$vg&15)<<16,cXg:(zb.YPd.awg&15)<<16,$Wg:(zb.YPd.Yvg&15)<<16,aXg:(zb.YPd.Zvg&15)<<16};zb.RKf=zb.xZc.G9f|zb.xZc.Tvg|zb.xZc.H9f|zb.xZc.I9f;zb.Zwg=zb.xZc.G9f|zb.xZc.H9f|zb.xZc.I9f;zb.YPg=function(e){zb.ijb||(zb.ijb=[],zb.ijb.push(4352),zb.ijb.push(4607),zb.ijb.push(11904),zb.ijb.push(40959),zb.ijb.push(44032),zb.ijb.push(55215),zb.ijb.push(63744),zb.ijb.push(64255),zb.ijb.push(65280),zb.ijb.push(65519),zb.ijb.push(131072),zb.ijb.push(173791),zb.ijb.push(194560),zb.ijb.push(195103));
if(e<zb.ijb[0])return!1;for(var f=zb.ijb,Da=zb.ijb.length,Ha=0;Ha<Da;Ha+=2)if(e>=f[Ha]&&e<=f[Ha+1])return!0;return!1};var gb=zb.tYb;zb.sZf=function(){};var Za=zb.YPd.J9f,bc={J1a:0,Ipc:1,D1b:2};Pa.prototype={sTf:function(e,f,Da,Ha,Ra){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.Vw?(this.ld.fillStyle=255==this.R&&255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.ld.fillRect(0,0,Ha,Ra)):(e=this.hwa,e.Hya.mPa.fillStyle=255==this.R&&
255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.hwa.Hya.mPa.fillRect(e.wc.Uc*e.Ta,e.wc.qa,Ha,Ra))},tTf:function(e,f,Da,Ha,Ra){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.Vw?(this.ld.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.ld.fillRect(0,0,Ha,Ra)):(e=this.hwa,e.Hya.mPa.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.hwa.Hya.mPa.fillRect(e.wc.Uc*e.Ta,e.wc.qa,Ha,Ra))},mJc:e,se:function(e,f){0!=e&&0!=f&&(this.Vw=
document.createElement("canvas"),this.Vw.width=0==e?1:e,this.Vw.height=0==f?1:f,this.ld=this.Vw.getContext("2d"),this.ld.globalCompositeOperation="source-in")}};Pa.prototype.mJc=Va.qf.fcb&&Va.qf.sKc?Pa.prototype.sTf:Pa.prototype.tTf;ab.prototype={sWf:function(e){var f;var Da=!1;Math.max(this.mla,this.Cua)>(null==e.T0a?0:e.T0a.ezb)/10&&(Da=!0);var Ha=f=0;Da?(this.kT.se(this.mla,this.Cua),e=this.kT.ld):(this.kT.hwa=e.T0a.hO(this.mla,this.Cua),e=this.kT.hwa.Hya.mPa,f=this.kT.hwa.wc.Uc*this.kT.hwa.Ta,
Ha=this.kT.hwa.wc.qa);0<this.mla&&0<this.Cua&&e.putImageData(gb.ZYa,f,Ha,0,0,this.mla,this.Cua);if(null!=gb.ZYa){var Ra=3;Da=4*(gb.width-this.mla);e=gb.ZYa.data;for(Ha=0;Ha<this.Cua;Ha++){for(f=0;f<this.mla;f++)e[Ra]=0,Ra+=4;Ra+=Da}}},Md:function(e,f,Da){var Ha=this.mla,Ra=this.Cua;if(null!=this.kT.Nfb)e.drawImage(this.kT.Nfb,0,0,Ha,Ra,f,Da,Ha,Ra),this.kT.Nfb=null;else if(null!=this.kT.Vw)e.drawImage(this.kT.Vw,0,0,Ha,Ra,f,Da,Ha,Ra);else{var Ia=this.kT.hwa;e.drawImage(Ia.Hya.uba,Ia.wc.Uc*Ia.Ta,Ia.wc.qa,
Ha,Ra,f,Da,Ha,Ra)}},syf:function(e,f,Da,Ha,Ra,Ia){if(null!=this.kT.Nfb)e.drawImage(this.kT.Nfb,Ia,0,Ha,Ra,f,Da,Ha,Ra),this.kT.Nfb=null;else if(null!=this.kT.Vw)e.drawImage(this.kT.Vw,Ia,0,Ha,Ra,f,Da,Ha,Ra);else{var Za=this.kT.hwa;e.drawImage(Za.Hya.uba,Za.wc.Uc*Za.Ta+Ia,Za.wc.qa,Ha,Ra,f,Da,Ha,Ra)}},tyf:function(e,f,Da,Ha){var Ra=f,Ia=Da;f+=this.mla;var Za=Da+this.Cua,Va=Da=0,Pa=this.mla,gb=this.Cua;Ra<Ha.ee&&(Da=Ha.ee-Ra,Ra+=Da,Pa-=Da);Ia<Ha.t&&(Va=Ha.t-Ia,Ia+=Va,gb-=Va);f>Ha.r&&(Pa-=f-Ha.r);Za>Ha.Ya&&
(gb-=Za-Ha.Ya);0>=Pa||0>=gb||(null!=this.kT.Nfb?(e.drawImage(this.kT.Nfb,Da,Va,Pa,gb,Ra,Ia,Pa,gb),this.kT.Nfb=null):null!=this.kT.Vw?e.drawImage(this.kT.Vw,Da,Va,Pa,gb,Ra,Ia,Pa,gb):(Ha=this.kT.hwa,e.drawImage(Ha.Hya.uba,Ha.wc.Uc*Ha.Ta+Da,Ha.wc.qa+Va,Pa,gb,Ra,Ia,Pa,gb)))},ozb:function(){null!=this.kT.hwa&&this.kT.hwa.Hya.ozb(this.kT.hwa)}};Ha.prototype={start:function(){},Edg:function(e,f,Da){this.xCb&&(Da.Ex(),this.xCb=!1);this.jH=this.pa+e/64*this.Omb;this.ORa=this.qa-f/64*this.Pmb;Da.Gj(this.jH,
this.ORa);return 0},w0f:function(e,f){return this.Edg(e.x,e.y,f)},wdg:function(e,f,Da){this.jH=this.pa+e/64*this.Omb;this.ORa=this.qa-f/64*this.Pmb;Da.Fc(this.jH,this.ORa);this.xCb=!0;return 0},yCf:function(e,f){return this.wdg(e.x,e.y,f)},Ncg:function(e,f,Da,Ha,Ra){e=this.pa+e/64*this.Omb;f=this.qa-f/64*this.Pmb;Da=this.pa+Da/64*this.Omb;Ha=this.qa-Ha/64*this.Pmb;Ra.Zd(1/3*(this.jH+2*e),1/3*(this.ORa+2*f),1/3*(2*e+Da),1/3*(2*f+Ha),Da,Ha);this.jH=Da;this.ORa=Ha;this.xCb=!0;return 0},X1e:function(e,
f,Da){return this.Ncg(e.x,e.y,f.x,f.y,Da)},Qcg:function(e,f,Da,Ha,Ra,Ia,Za){this.jH=this.pa+Ra/64*this.Omb;this.ORa=this.qa-Ia/64*this.Pmb;Za.Zd(this.pa+e/64*this.Omb,this.qa-f/64*this.Pmb,this.pa+Da/64*this.Omb,this.qa-Ha/64*this.Pmb,this.jH,this.ORa);this.xCb=!0;return 0},$xf:function(e,f,Da,Ha){return this.Qcg(e.x,e.y,f.x,f.y,Da.x,Da.y,Ha)},end:function(e){this.xCb&&(e.Ex(),this.xCb=!1)}};f.AscFonts.nzb=bc;f.AscFonts.KGf=function(){this.Q_d="undefined"==typeof Float64Array?Array(6):new Float64Array(6);
this.Y1b="undefined"==typeof Float64Array?Array(6):new Float64Array(6);this.K_f=!0;this.WQc=!1;this.nEb=1;this.g2b=this.sEb=0;this.a6b=this.VQc=!1;this.Mgb=0;this.b2b=new zb.Brf;this.oMd=0;this.yCa=this.W4=null;this.aef=1;this.Hud=this.Gud=-1;this.yua=!1;this.lla=this.koa=this.hya=this.Iwa=this.S_d=0;this.W1b=[];this.X1b=[];this.nv=null;this.kEb=this.lfe=this.abc=!0;this.Kjg=e;this.$_b=new Eb;this.eJf=function(e,f,Da){Da=zb.oae(e,f,Da);if(0!=Da&&this.abc){e=zb.oae(e,f,zb.RKf);if(0!=e)return Da;this.abc=
!1;return e}return Da};this.Ete=function(){var e=this.Q_d;this.VQc?(e[0]=1,e[1]=0,e[2]=.3090169943749):(e[0]=1,e[1]=0,e[2]=0);e[3]=1;e[4]=0;e[5]=0;this.Pfb()};this.eMf=function(){var e=this.Y1b;e[0]=1;e[1]=0;e[2]=0;e[3]=1;e[4]=0;e[5]=0;this.J7d()};this.J7d=function(){this.kEb=!0;var e=this.Y1b;1==e[0]&&0==e[1]&&0==e[2]&&1==e[3]&&(this.kEb=!1,this.Pfb())};this.Pfb=function(){var e=this.Q_d,f=this.Y1b;zb.hJf(this.W4,65536*(e[0]*f[0]+e[1]*f[2])>>0,65536*(e[0]*f[1]+e[1]*f[3])>>0,65536*(e[2]*f[0]+e[3]*
f[2])>>0,65536*(e[2]*f[1]+e[3]*f[3])>>0)};this.bSd=function(e,f,Da){f=f+.5>>0;Da=Da+.5>>0;var Ha=e/this.nEb;if((Ha=1.001<Ha||.999>Ha?!0:!1)||f!=this.sEb||Da!=this.g2b)this.sEb=f,this.g2b=Da,Ha&&(this.nEb=e,this.Pfb()),this.aef=this.sEb/72*this.nEb,this.oMd=zb.pae(this.W4,0,64*e>>0,f,Da),this.vhb()};this.vhb=function(){this.t3b();this.j3b();this.$_b&&this.$_b.vhb()};this.j3b=function(){this.W1b=[];this.X1b=[];this.$_b&&this.$_b.j3b()};this.t3b=function(){if(null!=this.nv&&null!=this.nv.T0a){var e=
this.W1b,f;for(f in e)null!=e[f].mz&&e[f].mz.ozb();e=this.X1b;for(f in e)null!=e[f].mz&&e[f].mz.ozb()}};this.Z0a=function(e,f,Da,Ha,Ra,Ia){var Za=this.Y1b,Va=Za[0]==e&&Za[1]==-f&&Za[2]==-Da&&Za[3]==Ha;if(Va&&Za[4]==Ra&&Za[5]==Ia)return!1;Za[0]=e;Za[1]=-f;Za[2]=-Da;Za[3]=Ha;Za[4]=Ra;Za[5]=Ia;Va||this.vhb();this.J7d();return!0};this.Ssf=function(e){var f=zb.Gsf(this.W4,e);if(0<f)return f;-1!=this.Hud&&61440>e&&(f=zb.Gsf(this.W4,e+61440));return f};this.r_b=function(f,Va,Pa,ob,Ra,Ia,Ab){var nb=new Da;
nb.I6f=f;var bb=this.yua?f:zb.Gsf(this.W4,f);0>=bb&&!this.yua&&-1!=this.Hud&&61440>f&&(bb=zb.Gsf(this.W4,f+61440));if(0>=bb){if(!0===Ab)return null;if(!this.yua&&this.$_b&&(bb=this.$_b.UKf(this,f,Va,Pa,ob,Ra,Ia)))return bb;if(0<=this.Gud)bb=this.Gud,nb.gba=bc.Ipc;else return nb.gba=bc.D1b,nb.ASc=-1,nb.Ana=(zb.Lvg(this.W4)>>6)/2,nb}else nb.gba=bc.J1a;nb.ASc=bb;nb.C0f=0;var Nc=this.EJf();if(this.yua||!Va||this.a6b||!zb.YPg(f))Nc|=zb.xZc.Svg;if(this.eJf(this.W4,bb,Nc))return nb;f=null;e!==ob&&(f=new Ha,
f.Omb=25.4/this.sEb,f.Pmb=25.4/this.g2b,Ra!==e&&(f.pa=Ra),Ia!==e&&(f.qa=Ia));Ra=zb.Rvg(this.W4,ob,f);if(null==Ra||e!==ob)return nb;ob=65535!=this.yCa.EDf&&800<=this.yCa.kqg?!0:!1;nb.Ana=Ra.RAc*this.aef/this.lla;this.a6b&&this.nv.rtf&&!ob&&(nb.Ana+=1);nb.ky.cQa=Ra.Rgg>>6;nb.ky.E3a=Ra.Qgg>>6;nb.ky.LWa=Ra.Tgg>>6;nb.ky.wia=Ra.Sgg>>6;Ia=nb.sfa;Ia.Kib=Ra.width>>6;Ia.YPb=Ra.height>>6;Ia.Lnd=Ra.mua>>6;Ia.Mnd=Ra.Kqa>>6;Ia.JJc=Ra.ela>>6;Ia.Ond=Ra.dFa>>6;Ia.Pnd=Ra.UDa>>6;Ia.Nnd=Ra.Aka>>6;if(Ab&&0==Ia.JJc&&0==
Ra.width)return null;if(!Va){if(Pa&&(Va=zb.F9f(this.W4,Za))){ob=zb.E9f(this.W4,Va,!1);Va=nb.ky;f=ob.data;Pa=ob.width;Ab=ob.rows;bb=ob.pitch;ob={yPc:0,zPc:0,pVf:0,oVf:0};Nc=!1;for(Ra=0;Ra<Pa;Ra++){var cc=4*Ra+3;for(Ia=0;Ia<Ab;Ia++,cc+=bb)if(0!=f[cc]){Nc=!0;break}if(Nc)break;ob.yPc++}Nc=!1;for(Ra=Pa-1;0<=Ra;Ra--){cc=4*Ra+3;for(Ia=0;Ia<Ab;Ia++,cc+=bb)if(0!=f[cc]){Nc=!0;break}if(Nc)break;ob.pVf++}Nc=!1;for(Ia=0;Ia<Ab;Ia++){cc=Ia*bb+3;for(Ra=0;Ra<Pa;Ra++,cc+=4)if(0!=f[cc]){Nc=!0;break}if(Nc)break;ob.zPc++}Nc=
!1;for(Ia=Ab-1;0<=Ia;Ia--){cc=Ia*bb+3;for(Ra=0;Ra<Pa;Ra++,cc+=4)if(0!=f[cc]){Nc=!0;break}if(Nc)break;ob.oVf++}if(null!=gb.ZYa)for(f=3,bb=4*(gb.width-Pa),Nc=gb.ZYa.data,Ia=0;Ia<Ab;Ia++){for(Ra=0;Ra<Pa;Ra++)Nc[f]=0,f+=4;f+=bb}Va.b4a=ob}return nb}nb.yEa=!0;Va=zb.F9f(this.W4,Za);if(!Va||0==Va.pitch)return nb;nb.mz=new ab;nb.mz.X1a=Va.left;nb.mz.KKc=Va.top;nb.mz.mla=Va.width;nb.mz.Cua=Va.rows;zb.E9f(this.W4,Va,!0);if(this.a6b&&this.K_f&&!ob)for(nb.mz.mla++,Va=nb.mz.mla,Pa=nb.mz.Cua,Ia=gb.ZYa.data,Ra=Ab=
0;Ab<Pa;++Ab,Ra+=gb.pitch)for(ob=Va-1;0<=ob;--ob)0!=ob&&(f=Ra+4*ob+3,Ia[f]=Va-1==ob?Ia[f-4]:Math.min(255,Ia[f-4]+Ia[f]));nb.mz.sWf(this.nv);return nb};this.Qaa=function(f){if(0>=f.fH)return!0;var Da=0,Ha=0;this.kEb&&this.Pfb();for(var Za=!1===this.yua?this.W1b:this.X1b,Ra=0;Ra<f.fH;++Ra){var Ia=f.pHb(Ra).GOa,Va=Za[Ia];e==Va&&(Za[Ia]=this.r_b(Ia,!1),Va=Za[Ia]);Ia=Va.ASc;var Pa=Va.gba;bc.D1b==Pa?(f.hIc(Ra,Ha,0),f.bIc(Ra,0,0,0,0),f.UKb(Ra,bc.D1b),Ha+=Va.Ana+this.Mgb,Da=0):(bc.Ipc==Pa?f.UKb(Ra,bc.Ipc):
f.UKb(Ra,bc.J1a),this.WQc&&Da&&0<Ra&&f.pHb(Ra).gba==f.pHb(Ra-1).gba&&(Ha+=this.mac(Da,Ia)),Da=f.XY+Ha,Pa=f.YY+0,f.hIc(Ra,f.pfa[4]+Da*f.pfa[0]+Pa*f.pfa[2]-f.XY,f.pfa[5]+Da*f.pfa[1]+Pa*f.pfa[3]-f.YY),Da=Va.sfa,f.uuf(Ra,Da.Kib,Da.YPb,Da.JJc,Da.Lnd,Da.Mnd,Da.Nnd,Da.Ond,Da.Pnd),f.bIc(Ra,Va.ky.cQa,Va.ky.wia,Va.ky.E3a,Va.ky.LWa),Ha+=Va.Ana+this.Mgb,Da=Ia)}f.Yvb=Ha+f.XY;f.RWb=0+f.YY};this.ic=function(f){if(0>=f.fH)return!0;this.kEb&&this.Pfb();for(var Da=0,Ha=0,Za=!1===this.yua?this.W1b:this.X1b,Ra=0;Ra<
f.fH;++Ra){var Ia=f.pHb(Ra),Va=Ia.GOa,Pa=Za[Va];if(e==Pa||null==Pa.mz)Za[Va]=this.r_b(Va,!0),Pa=Za[Va];Va=Pa.ASc;var gb=Pa.gba;bc.D1b==gb?(f.hIc(Ra,Ha,0),f.bIc(Ra,0,0,0,0),f.UKb(Ra,bc.D1b),Ha+=Pa.Ana+this.Mgb,Da=0):(bc.Ipc==gb?f.UKb(Ra,bc.Ipc):f.UKb(Ra,bc.J1a),this.WQc&&Da&&0<Ra&&f.pHb(Ra).gba==f.pHb(Ra-1).gba&&(Ha+=this.mac(Da,Va)),Da=f.XY+Ha,gb=f.YY+0,f.hIc(Ra,f.pfa[4]+Da*f.pfa[0]+gb*f.pfa[2]-f.XY,f.pfa[5]+Da*f.pfa[1]+gb*f.pfa[3]-f.YY),Ia.sfa=Pa.sfa,f.bIc(Ra,Pa.ky.cQa,Pa.ky.wia,Pa.ky.E3a,Pa.ky.LWa),
Ha+=Pa.Ana+this.Mgb,Ia.yEa=Pa.yEa,Ia.mz=Pa.mz,Da=Va)}f.Yvb=Ha+f.XY;f.RWb=0+f.YY};this.hFd=function(f){this.kEb&&this.Pfb();var Da=f.XK[0],Ha=Da.GOa,Za=!1===this.yua?this.W1b:this.X1b,Ra=Za[Ha];if(e==Ra||null==Ra.mz&&!1===Ra.yEa)Za[Ha]=this.r_b(Ha,!0),Ra=Za[Ha];if(Ra)if(Ha=Ra.gba,Da.gba=Ra.gba,bc.D1b==Ha)Da.Xy=0,Da.Yx=0,Da.aGa=0,Da.Rxa=0,Da.dQa=0,Da.$Fa=0;else{Ha=f.XY;Za=f.YY;var Ia=f.pfa;Da.Xy=Ia[4]+Ha*Ia[0]+Za*Ia[2]-f.XY;Da.Yx=Ia[5]+Ha*Ia[1]+Za*Ia[3]-f.YY;Da.sfa=Ra.sfa;Da.yEa=Ra.yEa;Da.mz=Ra.mz;
f.Yvb=Ra.Ana+this.Mgb+f.XY;f.RWb=f.YY}};this.s_=function(f,Da){this.kEb&&this.Pfb();var Ha=!1===this.yua?this.W1b:this.X1b,Za=Ha[f];e==Za&&(Ha[f]=this.r_b(f,!1,Da),Za=Ha[f]);return Za};this.FJf=function(e,f,Da,Ha){this.kEb&&this.Pfb();this.r_b(e,!1,!1,f,Da,Ha)};this.Vsf=function(e,f){var Da=e.fH;if(!(0>=Da))for(var Ha=0;Ha<Da;++Ha){var Ra=e.XK[Ha],Ia=e.XY+25.4*Ra.Xy/this.sEb,Za=e.YY+25.4*Ra.Yx/this.g2b;f.xj();this.FJf(Ra.GOa,f,Ia,Za);f.et();f.Yt()}};this.EJf=function(){return this.abc&&this.lfe?this.nv.aRd:
zb.RKf};this.mac=function(e,f){return zb.Mvg(this.W4,e,f)>>6};this.jEa=function(e){this.yua!=e&&(this.yua=e)};this.suf=function(e){this.Mgb=e};this.EKf=function(){return this.a6b?!0:-1!=this.yCa.KDa.indexOf("Bold")?!0:!1};this.IKf=function(){return this.VQc?!0:-1!=this.yCa.KDa.indexOf("Italic")?!0:!1};this.wuf=function(e){this.VQc!=e&&(this.vhb(),this.VQc=e,this.Ete())};this.vuf=function(e){this.a6b!=e&&(this.vhb(),this.a6b=e)};this.VQd=function(){return 0==this.oMd};this.Q5a=function(){return this.Iwa};
this.iSa=function(){return this.hya};this.UG=function(){return this.koa};this.mPd=function(){this.lfe=this.abc=!0};this.Hhg=function(){var e=this.yCa,f=[];f.push(e.MQa);65535!=e.EDf?(f.push(e.b1f),f.push(-e.c1f)):(f.push(e.Dlg),f.push(e.Elg));return f};this.vyg=function(e,f){this.W4=e;this.yCa=new zb.iug;this.yCa.load(this.W4);this.lla=this.yCa.MQa;this.Iwa=this.yCa.z5;this.hya=this.yCa.zZ;this.koa=this.yCa.height;if(f.wtf&&65535!=this.yCa.EDf)if(f.qFd){var Da=this.yCa.b1f,Ha=-this.yCa.c1f;if(0!=
(this.yCa.iqg&770703360)){var Ra=.3*(Da-Ha)>>0;Da+=Ra+1>>1;Ha-=Ra>>1}this.yCa.height<Da-Ha&&(this.Iwa=Da,this.hya=Ha,this.koa=Da-Ha)}else 128==(this.yCa.fqg&128)&&(this.Iwa=this.yCa.$0f,this.hya=this.yCa.a1f,this.koa=this.yCa.$0f-this.yCa.a1f+this.yCa.hqg);this.S_d=this.yCa.p2b;this.Gud=this.yCa.jqg;this.Hud=this.yCa.gqg;this.oMd=zb.pae(e,0,64*this.nEb,0,0);this.eMf();this.Ete();!0===f.WQc&&(this.WQc=0!=(this.yCa.VZ&64)?!0:!1);if(0!=this.yCa.YCf.length)for(this.Kjg=[],e=this.yCa.YCf.length-1;0<=e;e--)this.Kjg[this.yCa.YCf[e]>>
6]=!0}};f.AscFonts.yEb()})(window);"use strict";(function(f){function e(){this.lL=Pa.dvg();this.ACa=null;this.DDf=function(e,f){e=Pa.gJf(this.lL,e,f);if(!e)return null;f=new Pa.KGf;f.vyg(e,this.ACa);return f.VQd()?f:null};this.r1d=function(e,f){f=e&&f?Pa.Syg:Pa.Ryg;this.ACa.aRd=e?Pa.Zwg:Pa.RKf;Pa.bwg(this.lL,f)}}var Pa=f.AscFonts;f.AscFonts.Ayf=function(f){var bb=new e;bb.ACa=f;bb.r1d(f.nId,f.oId);f.Rzb=bb;Pa.sZf()};f.AscFonts.EMg=function(){};f.AscFonts.yEb()})(window);
