/*
 * Copyright (C) Ascensio System SIA 2012-2020. All rights reserved
 *
 * https://www.onlyoffice.com/
 *
 * Version: 0.0.0 (build:0)
 */

(function(f,e){function Ia(e){return $a.locateFile?$a.locateFile(e,gf):gf+e}function cb(e,f,y){var Ma=f+y;for(y=f;e[y]&&!(y>=Ma);)++y;if(16<y-f&&e.subarray&&Td)return Td.decode(e.subarray(f,y));for(Ma="";f<y;){var Pa=e[f++];if(Pa&128){var Va=e[f++]&63;if(192==(Pa&224))Ma+=String.fromCharCode((Pa&31)<<6|Va);else{var Ta=e[f++]&63;Pa=224==(Pa&240)?(Pa&15)<<12|Va<<6|Ta:(Pa&7)<<18|Va<<12|Ta<<6|e[f++]&63;65536>Pa?Ma+=String.fromCharCode(Pa):(Pa-=65536,Ma+=String.fromCharCode(55296|Pa>>10,56320|Pa&1023))}}else Ma+=
String.fromCharCode(Pa)}return Ma}function Xa(e){hi=e;$a.HEAP8=id=new Int8Array(e);$a.HEAP16=new Int16Array(e);$a.HEAP32=rc=new Int32Array(e);$a.HEAPU8=qb=new Uint8Array(e);$a.HEAPU16=new Uint16Array(e);$a.HEAPU32=new Uint32Array(e);$a.HEAPF32=new Float32Array(e);$a.HEAPF64=new Float64Array(e)}function ib(f){for(;0<f.length;){var y=f.shift();if("function"==typeof y)y();else{var Ma=y.func;"number"===typeof Ma?y.Z1f===e?$a.dynCall_v(Ma):$a.dynCall_vi(Ma,y.Z1f):Ma(y.Z1f===e?null:y.Z1f)}}}function y(e){if($a.onAbort)$a.onAbort(e);
e+="";kg(e);Di(e);Xc=!0;throw new WebAssembly.g$g("abort("+e+"). Build with -s ASSERTIONS=1 for more info.");}function kb(e){return String.prototype.startsWith?e.startsWith("data:application/octet-stream;base64,"):0===e.indexOf("data:application/octet-stream;base64,")}function rb(){try{if(ue)return new Uint8Array(ue);if(Ie)return Ie(rk);throw"both async and sync fetching of the wasm failed";}catch(yc){y(yc)}}function mb(){return ue||!qe&&!kf||"function"!==typeof Xb?new Promise(function(e){e(rb())}):
Xb(rk,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+rk+"'";return e.arrayBuffer()}).catch(function(){return rb()})}function Ta(e,f,y,Ma){e|=0;f|=0;y|=0;Ma|=0;var Pa=0;qc=qc+1|0;for(rc[e>>2]=qc;(Pa|0)<(Ma|0);){if(0==(rc[y+(Pa<<3)>>2]|0))return rc[y+(Pa<<3)>>2]=qc,rc[y+((Pa<<3)+4)>>2]=f,rc[y+((Pa<<3)+8)>>2]=0,gh=Ma|0,y|0;Pa=Pa+1|0}Ma=2*Ma|0;y=Vk(y|0,8*(Ma+1|0)|0)|0;y=Ta(e|0,f|0,y|0,Ma|0)|0;gh=Ma|0;return y|0}function yb(){if(!yb.Gta){var e={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Pa},f;for(f in un)e[f]=un[f];var y=[];for(f in e)y.push(f+"="+e[f]);yb.Gta=y}return yb.Gta}function Va(){function e(){if(!Me&&(Me=!0,!Xc)){ib($g);ib(ek);if($a.onRuntimeInitialized)$a.onRuntimeInitialized();if($a.postRun)for("function"==typeof $a.postRun&&($a.postRun=[$a.postRun]);$a.postRun.length;)ah.unshift($a.postRun.shift());
ib(ah)}}if(!(0<Cc)){if($a.preRun)for("function"==typeof $a.preRun&&($a.preRun=[$a.preRun]);$a.preRun.length;)og.unshift($a.preRun.shift());ib(og);0<Cc||($a.setStatus?($a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){$a.setStatus("")},1);e()},1)):e())}}function zb(){this.C3d=this.fTc=this.j9b=this.vM=this.GJc=this.z0=this.height=this.X_=this.W7=this.MUa=0;this.nHa=this.j7="";this.ryg=this.syg=this.WCg=this.YCg=this.XCg=this.wcg=this.vcg=this.ZCg=this.ycg=this.xcg=this.VCg=this.$Cg=
this.tQf=0;this.PPf=[]}function Ac(){this.$Rc=this.pIc=this.uHa=this.MIa=this.Nna=this.tua=this.Wxa=this.voa=this.height=this.width=this.wtg=this.utg=this.xtg=this.vtg=0}function ec(){this.mode=this.pitch=this.rows=this.width=this.top=this.left=0}var vc=f.AscFonts,Xb=f.fetch,Ma=null;f.AscDesktopEditor&&document.currentScript&&0==document.currentScript.src.indexOf("file:///")?(Xb=e,Ma=function(){var e="ascdesktop://fonts/"+rk.substr(8);return new Promise(function(f){var y=new XMLHttpRequest;y.open("GET",
e,!0);y.responseType="arraybuffer";y.overrideMimeType?y.overrideMimeType("text/plain; charset=x-user-defined"):y.setRequestHeader("Accept-Charset","x-user-defined");y.onload=function(){200==this.status&&f(new Uint8Array(this.response))};y.send(null)})}):Ma=function(){return mb()};var $a="undefined"!==typeof $a?$a:{},jb={};for($e in $a)$a.hasOwnProperty($e)&&(jb[$e]=$a[$e]);var Pa="./this.program",qe=!0,kf=!1,gf="",Ie;if(qe||kf)kf?gf=self.location.href:document.currentScript&&(gf=document.currentScript.src),
gf=0!==gf.indexOf("blob:")?gf.substr(0,gf.lastIndexOf("/")+1):"",kf&&(Ie=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.responseType="arraybuffer";f.send(null);return new Uint8Array(f.response)});var kg=$a.print||console.log.bind(console),Di=$a.printErr||console.warn.bind(console);for($e in jb)jb.hasOwnProperty($e)&&($a[$e]=jb[$e]);jb=null;$a.thisProgram&&(Pa=$a.thisProgram);var gh=0,ue;$a.wasmBinary&&(ue=$a.wasmBinary);"object"!==typeof WebAssembly&&Di("no native wasm support detected");
var Wc;jb=new WebAssembly.Table({initial:573,maximum:573,element:"anyfunc"});var Xc=!1,Td="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):e;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var id,qb,rc;var $e=$a.TOTAL_MEMORY||16777216;if(Wc=$a.wasmMemory?$a.wasmMemory:new WebAssembly.Memory({initial:$e/65536}))var hi=Wc.buffer;$e=hi.byteLength;Xa(hi);rc[27492]=5353008;var og=[],$g=[],ek=[],ah=[function(){f.AscFonts.$Jb()}],Cc=0,Oc=null,kc=null;$a.preloadedImages={};$a.preloadedAudios=
{};var rk="fonts.wasm";kb(rk)||(rk=Ia(rk));$g.push({func:function(){Gf()}});var bh={MTa:[null,[],[]],g4g:function(e,f){var y=bh.MTa[e];0===f||10===f?((1===e?kg:Di)(cb(y,0)),y.length=0):y.push(f)},wae:0,get:function(){bh.wae+=4;return rc[bh.wae-4>>2]},R5a:function(){var e=bh.get();return e?cb(qb,e,void 0):""},Cah:function(){var e=bh.get();bh.get();return e},Iah:function(){bh.get()}},qc=0,un={},Kd={v:function(){},f:function(e,f){bh.wae=f;return 0},i:function(f,Ma){bh.wae=Ma;try{var Pa=bh.R5a(),Va=bh.get(),
Ta=bh.get();return e.open(Pa,Va,Ta).wah}catch(hd){return"undefined"!==typeof e&&hd instanceof e.$kg||y(hd),-hd.gwg}},u:function(e,f){bh.wae=f;return 0},e:function(){},b:function(e,f){ce(e,f||1);throw"longjmp";},n:function(e,f,y){qb.set(qb.subarray(f,f+y),e)},p:function(e){var f=id.length;if(2147418112<e)return!1;for(var y=1;4>=y;y*=2){var Ma=f*(1+.2/y);Ma=Math.min(Ma,e+100663296);Ma=Math.max(16777216,e,Ma);0<Ma%65536&&(Ma+=65536-Ma%65536);a:{try{Wc.grow(Math.min(2147418112,Ma)-hi.byteLength+65535>>
16);Xa(Wc.buffer);var Pa=1;break a}catch(hd){}Pa=void 0}if(Pa)return!0}return!1},q:function(e,f){var y=0;yb().forEach(function(Ma,Pa){var Va=f+y;Pa=rc[e+4*Pa>>2]=Va;for(Va=0;Va<Ma.length;++Va)id[Pa++>>0]=Ma.charCodeAt(Va);id[Pa>>0]=0;y+=Ma.length+1});return 0},r:function(e,f){var y=yb();rc[e>>2]=y.length;var Ma=0;y.forEach(function(e){Ma+=e.length+1});rc[f>>2]=Ma;return 0},g:function(){return 0},t:function(f,Ma,Pa,Va){try{var Ta=bh.Hah(f),Ia=bh.sah(Ta,Ma,Pa);rc[Va>>2]=Ia;return 0}catch(Jc){return"undefined"!==
typeof e&&Jc instanceof e.$kg||y(Jc),Jc.gwg}},m:function(){return 0},s:function(f,Ma,Pa,Va){try{for(var Ta=0,Ia=0;Ia<Pa;Ia++){for(var jb=rc[Ma+8*Ia>>2],w=rc[Ma+(8*Ia+4)>>2],Ra=0;Ra<w;Ra++)bh.g4g(f,qb[jb+Ra]);Ta+=w}rc[Va>>2]=Ta;return 0}catch(vn){return"undefined"!==typeof e&&vn instanceof e.$kg||y(vn),vn.gwg}},a:function(){return gh|0},k:function(e,f,y){var Ma=yd();try{return Mc(e,f,y)}catch(jg){Fe(Ma);if(jg!==jg+0&&"longjmp"!==jg)throw jg;ce(1,0)}},o:function(e,f,y,Ma){var Pa=yd();try{return Cf(e,
f,y,Ma)}catch(hd){Fe(Pa);if(hd!==hd+0&&"longjmp"!==hd)throw hd;ce(1,0)}},j:function(e,f,y,Ma,Pa){var Va=yd();try{return Cd(e,f,y,Ma,Pa)}catch(Jc){Fe(Va);if(Jc!==Jc+0&&"longjmp"!==Jc)throw Jc;ce(1,0)}},l:function(e,f,y){var Ma=yd();try{If(e,f,y)}catch(jg){Fe(Ma);if(jg!==jg+0&&"longjmp"!==jg)throw jg;ce(1,0)}},memory:Wc,h:Ta,c:function(e){gh=e|0},table:jb,d:function(e,f,y){e|=0;f|=0;y|=0;for(var Ma=0,Pa;(Ma|0)<(y|0);){Pa=rc[f+(Ma<<3)>>2]|0;if(0==(Pa|0))break;if((Pa|0)==(e|0))return rc[f+((Ma<<3)+4)>>
2]|0;Ma=Ma+1|0}return 0}};jb=function(){function e(e){$a.asm=e.exports;Cc--;$a.monitorRunDependencies&&$a.monitorRunDependencies(Cc);0==Cc&&(null!==Oc&&(clearInterval(Oc),Oc=null),kc&&(e=kc,kc=null,e()))}function f(f){e(f.instance)}function Pa(e){return Ma().then(function(e){return WebAssembly.instantiate(e,Va)}).then(e,function(e){Di("failed to asynchronously prepare wasm: "+e);y(e)})}var Va={a:Kd};Cc++;$a.monitorRunDependencies&&$a.monitorRunDependencies(Cc);if($a.instantiateWasm)try{return $a.instantiateWasm(Va,
e)}catch(jg){return Di("Module.instantiateWasm callback failed with error: "+jg),!1}(function(){if(ue||"function"!==typeof WebAssembly.instantiateStreaming||kb(rk)||"function"!==typeof Xb)return Pa(f);Xb(rk,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,Va).then(f,function(e){Di("wasm streaming compile failed: "+e);Di("falling back to ArrayBuffer instantiation");Pa(f)})})})();return{}}();$a.asm=jb;var Gf=$a.___wasm_call_ctors=function(){return(Gf=$a.___wasm_call_ctors=
$a.asm.w).apply(null,arguments)};$a._FT_Load_Glyph=function(){return($a._FT_Load_Glyph=$a.asm.x).apply(null,arguments)};$a._FT_Set_Transform=function(){return($a._FT_Set_Transform=$a.asm.y).apply(null,arguments)};$a._FT_Done_Face=function(){return($a._FT_Done_Face=$a.asm.z).apply(null,arguments)};$a._FT_Set_Char_Size=function(){return($a._FT_Set_Char_Size=$a.asm.A).apply(null,arguments)};$a._FT_Get_Glyph=function(){return($a._FT_Get_Glyph=$a.asm.B).apply(null,arguments)};$a._FT_Done_FreeType=function(){return($a._FT_Done_FreeType=
$a.asm.C).apply(null,arguments)};$a._malloc=function(){return($a._malloc=$a.asm.D).apply(null,arguments)};var Vk=$a._realloc=function(){return(Vk=$a._realloc=$a.asm.E).apply(null,arguments)};$a._free=function(){return($a._free=$a.asm.F).apply(null,arguments)};$a._ASC_FT_Malloc=function(){return($a._ASC_FT_Malloc=$a.asm.G).apply(null,arguments)};$a._ASC_FT_Free=function(){return($a._ASC_FT_Free=$a.asm.H).apply(null,arguments)};$a._ASC_FT_Init=function(){return($a._ASC_FT_Init=$a.asm.I).apply(null,
arguments)};$a._ASC_FT_Open_Face=function(){return($a._ASC_FT_Open_Face=$a.asm.J).apply(null,arguments)};$a._ASC_FT_SetCMapForCharCode=function(){return($a._ASC_FT_SetCMapForCharCode=$a.asm.K).apply(null,arguments)};$a._ASC_FT_GetFaceInfo=function(){return($a._ASC_FT_GetFaceInfo=$a.asm.L).apply(null,arguments)};$a._ASC_FT_GetFaceMaxAdvanceX=function(){return($a._ASC_FT_GetFaceMaxAdvanceX=$a.asm.M).apply(null,arguments)};$a._ASC_FT_GetKerningX=function(){return($a._ASC_FT_GetKerningX=$a.asm.N).apply(null,
arguments)};$a._ASC_FT_Glyph_Get_CBox=function(){return($a._ASC_FT_Glyph_Get_CBox=$a.asm.O).apply(null,arguments)};$a._ASC_FT_Get_Glyph_Measure_Params=function(){return($a._ASC_FT_Get_Glyph_Measure_Params=$a.asm.P).apply(null,arguments)};$a._ASC_FT_Get_Glyph_Render_Params=function(){return($a._ASC_FT_Get_Glyph_Render_Params=$a.asm.Q).apply(null,arguments)};$a._ASC_FT_Get_Glyph_Render_Buffer=function(){return($a._ASC_FT_Get_Glyph_Render_Buffer=$a.asm.R).apply(null,arguments)};$a._ASC_FT_Set_Transform=
function(){return($a._ASC_FT_Set_Transform=$a.asm.S).apply(null,arguments)};$a._ASC_FT_Set_TrueType_HintProp=function(){return($a._ASC_FT_Set_TrueType_HintProp=$a.asm.T).apply(null,arguments)};var ce=$a._setThrew=function(){return(ce=$a._setThrew=$a.asm.U).apply(null,arguments)},If=$a.dynCall_vii=function(){return(If=$a.dynCall_vii=$a.asm.V).apply(null,arguments)},Mc=$a.dynCall_iii=function(){return(Mc=$a.dynCall_iii=$a.asm.W).apply(null,arguments)},Cf=$a.dynCall_iiii=function(){return(Cf=$a.dynCall_iiii=
$a.asm.X).apply(null,arguments)},Cd=$a.dynCall_iiiii=function(){return(Cd=$a.dynCall_iiiii=$a.asm.Y).apply(null,arguments)},yd=$a.stackSave=function(){return(yd=$a.stackSave=$a.asm.Z).apply(null,arguments)},Fe=$a.stackRestore=function(){return(Fe=$a.stackRestore=$a.asm._).apply(null,arguments)};$a.dynCall_vi=function(){return($a.dynCall_vi=$a.asm.$).apply(null,arguments)};$a.asm=jb;var Me;kc=function Uh(){Me||Va();Me||(kc=Uh)};$a.run=Va;if($a.preInit)for("function"==typeof $a.preInit&&($a.preInit=
[$a.preInit]);0<$a.preInit.length;)$a.preInit.pop()();Va();f.AscFonts=f.AscFonts||{};vc=f.AscFonts;vc.aIg=function(){return $a._ASC_FT_Init()};vc.ELg=35;vc.s$g=38;vc.FLg=40;vc.ZIg=function(e,f){$a._ASC_FT_Set_TrueType_HintProp(e,f)};vc.bIg=function(e){var f=$a._ASC_FT_Malloc(e.size);$a.HEAP8.set(e.data,f);return{gVg:!0,data:f,oi:e.size}};vc.dZd=function(e){var f=vc.bbc[e];f&&!0!==f.gVg&&(f=vc.bIg(vc.bbc[e]),vc.bbc[e]=null,vc.bbc[e]=f)};zb.prototype.load=function(e){if(e=$a._ASC_FT_GetFaceInfo(e)){var f=
new Int32Array($a.HEAP8.buffer,e,Math.min($a.HEAP8.length-e>>2,250)),y=0;this.MUa=Math.abs(f[y++]);this.W7=f[y++];this.X_=f[y++];this.height=f[y++];this.z0=f[y++];this.GJc=f[y++];this.vM=f[y++];this.j9b=f[y++];this.fTc=f[y++];this.C3d=f[y++];for(var Ma=f[y++];Ma;)this.j7+=String.fromCharCode(Ma),Ma=f[y++];for(Ma=f[y++];Ma;)this.nHa+=String.fromCharCode(Ma),Ma=f[y++];this.tQf=f[y++];this.$Cg=f[y++];this.VCg=f[y++];this.xcg=f[y++];this.ycg=f[y++];this.ZCg=f[y++];this.vcg=f[y++];this.wcg=f[y++];this.XCg=
f[y++];y++;this.YCg=vc.CX.TS(f[y++]);y++;y++;y++;y++;this.WCg=f[y++];this.syg=f[y++];this.ryg=f[y++];Ma=f[y++];for(var Pa=0;Pa<Ma;Pa++)this.PPf.push(f[y++]);$a._ASC_FT_Free(e)}};vc.gHg=zb;vc.S8g=Ac;vc.R8g=ec;vc.$Vf=function(e,f,y){return $a._ASC_FT_Open_Face(e,f.data,f.oi,y)};vc.OIg=function(e,f,y){e=$a._ASC_FT_Get_Glyph_Measure_Params(e,f?1:0);if(!e)return null;var Ma=15;f&&(Ma=$a.HEAP32[e>>2]);var Pa=new Int32Array($a.HEAP8.buffer,e,Ma),Va=new Ac;Va.vtg=Pa[1];Va.xtg=Pa[2];Va.utg=Pa[3];Va.wtg=Pa[4];
Va.width=Pa[5];Va.height=Pa[6];Va.voa=Pa[7];Va.Wxa=Pa[8];Va.tua=Pa[9];Va.Nna=Pa[10];Va.MIa=Pa[11];Va.uHa=Pa[12];Va.pIc=Pa[13];Va.$Rc=Pa[14];if(f){y.start(f);for(var w=15;w<Ma;)switch(Pa[w++]){case 0:y.fqg(Pa[w++],Pa[w++],f);break;case 1:y.Xpg(Pa[w++],Pa[w++],f);break;case 2:y.lpg(Pa[w++],Pa[w++],Pa[w++],Pa[w++],f);break;case 3:y.opg(Pa[w++],Pa[w++],Pa[w++],Pa[w++],Pa[w++],Pa[w++],f)}y.end(f)}$a._ASC_FT_Free(e);return Va};vc.hlg=function(e,f){e=$a._ASC_FT_Get_Glyph_Render_Params(e,f);if(!e)return null;
f=new Int32Array($a.HEAP8.buffer,e,6);var y=new ec;y.left=f[0];y.top=f[1];y.width=f[2];y.rows=f[3];y.pitch=f[4];y.mode=f[5];$a._ASC_FT_Free(e);return y};vc.Nje=$a._FT_Load_Glyph;vc.aWf=$a._ASC_FT_Set_Transform;vc.Oje=$a._FT_Set_Char_Size;vc.aFf=$a._ASC_FT_SetCMapForCharCode;vc.JIg=$a._ASC_FT_GetKerningX;vc.IIg=$a._ASC_FT_GetFaceMaxAdvanceX;vc.glg=function(e,f,y){e=$a._ASC_FT_Get_Glyph_Render_Buffer(e);e=new Uint8Array($a.HEAP8.buffer,e,f.pitch*f.rows);if(!y)return e;vc.h4b.YI(f.width,f.rows);y=0;
var Ma=vc.h4b.p2a.data;if(f.pitch>=f.width)for(var Pa=0;Pa<f.rows;++Pa,y+=f.pitch){var Va=3+Pa*vc.h4b.pitch;for(var w=0;w<f.width;w++,Va+=4)Ma[Va]=e[y+w]}else{var Ra,Ta;for(Pa=0;Pa<f.rows;++Pa,y+=f.pitch)for(Va=3+Pa*vc.h4b.pitch,w=Ta=Ra=0;w<f.width;w++,Va+=4,Ra++)8==Ra&&(Ra=0,Ta++),Ma[Va]=e[y+Ta]&1<<7-Ra?255:0}};vc.$Jb()})(window,void 0);"use strict";
(function(f,e){function Ia(){this.gd=this.Rx=null;this.B=this.G=this.R=0;this.Rkb=this.Pza=null}function cb(){this.mya=this.Coa=this.kSc=this.j6a=0;this.DU=new Ia}function Xa(){this.ola=this.e0a=this.T7a=this.YTa=0;this.x8a=null}function ib(){this.Gwd=this.Iwd=this.Hwd=this.gRc=this.Fwd=this.Ewd=this.kWb=this.Znb=0}function y(){this.eig;this.zda;this.Xbg;this.s_c;this.dra;this.hz=new Xa;this.cia=new ib;this.eIa=!1;this.fA=null}function kb(){this.la=this.ka=0;this.gsb=25.4/72;this.hsb=25.4/72;this.VHb=
!1;this.QVa=this.fI=this.Ouc=this.shift=0}function rb(){this.r6b={};this.HXf=function(f,y,Va,Ia,Ma,$a,jb){var Pa=f.Sv,Xa=mb.tp.mBa(y);if(e===Xa||""==Xa)return null;var ib=this.r6b[Xa];if(!ib){ib=mb.o0a[mb.Jeb[Xa]];var Xb=mb.v$a.VIa;f.sXf()&&(Xb|=mb.v$a.Tna);f.xXf()&&(Xb|=mb.v$a.Una);ib=ib.FH(Ta.TK,Pa,f.KJb,Xb,f.QJb,f.e9b,e,!0);if(!ib)return null;ib.OYd();this.r6b[Xa]=ib}if(!ib)return null;ib.w0d(f.KJb,f.QJb,f.e9b);f=f.X8b;Pa=ib.X8b;Pa[0]=f[0];Pa[1]=f[1];Pa[2]=f[2];Pa[3]=f[3];Pa[4]=f[4];Pa[5]=f[5];
ib.Tkb();return ib.d6b(y,Va,Ia,Ma,$a,jb,!0)};this.Dmb=function(){if(!this.$je){this.$je=!0;for(var e in this.r6b)this.r6b[e].Dmb();delete this.$je}};this.c$b=function(){if(!this.Zje){this.Zje=!0;for(var e in this.r6b)this.r6b[e].c$b();delete this.Zje}}}var mb=f.AscFonts,Ta=f.AscCommon;mb.F6c={ilg:0,u9g:1,QIg:2,w9g:4,PIg:8,C9g:16,p9g:32,o9g:64,v9g:128,q9g:512,t9g:1024,r9g:2048,s9g:4096,jlg:8192,klg:32768,m9g:1048576,n9g:2097152,l9g:4194304};mb.DZd={llg:0,XIg:1,YIg:2,VIg:3,WIg:4,E9g:5};mb.D9g={B9g:(mb.DZd.llg&
15)<<16,z9g:(mb.DZd.XIg&15)<<16,A9g:(mb.DZd.YIg&15)<<16,x9g:(mb.DZd.VIg&15)<<16,y9g:(mb.DZd.WIg&15)<<16};mb.EXf=mb.F6c.ilg|mb.F6c.QIg|mb.F6c.jlg|mb.F6c.klg;mb.RJg=mb.F6c.ilg|mb.F6c.jlg|mb.F6c.klg;mb.z2g=function(e){mb.Aob||(mb.Aob=[],mb.Aob.push(4352),mb.Aob.push(4607),mb.Aob.push(11904),mb.Aob.push(40959),mb.Aob.push(44032),mb.Aob.push(55215),mb.Aob.push(63744),mb.Aob.push(64255),mb.Aob.push(65280),mb.Aob.push(65519),mb.Aob.push(131072),mb.Aob.push(173791),mb.Aob.push(194560),mb.Aob.push(195103));
if(e<mb.Aob[0])return!1;for(var f=mb.Aob,y=mb.Aob.length,Va=0;Va<y;Va+=2)if(e>=f[Va]&&e<=f[Va+1])return!0;return!1};var yb=mb.h4b;mb.F$f=function(){};var Va=mb.DZd.llg,zb={V5a:0,Ywc:1,D8b:2};Ia.prototype={C4f:function(e,f,y,Va,Ma){if(e!=this.R||f!=this.G||y!=this.B)this.R=e,this.G=f,this.B=y,null!=this.Rx?(this.gd.fillStyle=255==this.R&&255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.gd.fillRect(0,0,Va,Ma)):(e=this.Pza,e.fCa.aTa.fillStyle=255==this.R&&255==
this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.Pza.fCa.aTa.fillRect(e.qc.Tc*e.za,e.qc.la,Va,Ma))},D4f:function(e,f,y,Va,Ma){if(e!=this.R||f!=this.G||y!=this.B)this.R=e,this.G=f,this.B=y,null!=this.Rx?(this.gd.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.gd.fillRect(0,0,Va,Ma)):(e=this.Pza,e.fCa.aTa.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.Pza.fCa.aTa.fillRect(e.qc.Tc*e.za,e.qc.la,Va,Ma))},KQc:e,te:function(e,f){0!=e&&0!=f&&(this.Rx=document.createElement("canvas"),
this.Rx.width=0==e?1:e,this.Rx.height=0==f?1:f,this.gd=this.Rx.getContext("2d"),this.gd.globalCompositeOperation="source-in")}};Ia.prototype.KQc=Ta.Se.d2a&&Ta.Se.SRc?Ia.prototype.C4f:Ia.prototype.D4f;cb.prototype={A7f:function(e){var f;var y=!1;Math.max(this.Coa,this.mya)>(null==e.Qza?0:e.Qza.HEb)/10&&(y=!0);var Va=f=0;y?(this.DU.te(this.Coa,this.mya),e=this.DU.gd):(this.DU.Pza=e.Qza.oP(this.Coa,this.mya),e=this.DU.Pza.fCa.aTa,f=this.DU.Pza.qc.Tc*this.DU.Pza.za,Va=this.DU.Pza.qc.la);0<this.Coa&&0<
this.mya&&e.putImageData(yb.p2a,f,Va,0,0,this.Coa,this.mya);if(null!=yb.p2a){var Ma=3;y=4*(yb.width-this.Coa);e=yb.p2a.data;for(Va=0;Va<this.mya;Va++){for(f=0;f<this.Coa;f++)e[Ma]=0,Ma+=4;Ma+=y}}},Md:function(e,f,y){var Va=this.Coa,Ma=this.mya;if(null!=this.DU.Rkb)e.drawImage(this.DU.Rkb,0,0,Va,Ma,f,y,Va,Ma),this.DU.Rkb=null;else if(null!=this.DU.Rx)e.drawImage(this.DU.Rx,0,0,Va,Ma,f,y,Va,Ma);else{var Ta=this.DU.Pza;e.drawImage(Ta.fCa.Kda,Ta.qc.Tc*Ta.za,Ta.qc.la,Va,Ma,f,y,Va,Ma)}},ZKf:function(e,
f,y,Va,Ma,Ta){if(null!=this.DU.Rkb)e.drawImage(this.DU.Rkb,Ta,0,Va,Ma,f,y,Va,Ma),this.DU.Rkb=null;else if(null!=this.DU.Rx)e.drawImage(this.DU.Rx,Ta,0,Va,Ma,f,y,Va,Ma);else{var Ia=this.DU.Pza;e.drawImage(Ia.fCa.Kda,Ia.qc.Tc*Ia.za+Ta,Ia.qc.la,Va,Ma,f,y,Va,Ma)}},$Kf:function(e,f,y,Va){var Ma=f,Ta=y;f+=this.Coa;var Ia=y+this.mya,Pa=y=0,Xa=this.Coa,ib=this.mya;Ma<Va.ie&&(y=Va.ie-Ma,Ma+=y,Xa-=y);Ta<Va.t&&(Pa=Va.t-Ta,Ta+=Pa,ib-=Pa);f>Va.r&&(Xa-=f-Va.r);Ia>Va.Xa&&(ib-=Ia-Va.Xa);0>=Xa||0>=ib||(null!=this.DU.Rkb?
(e.drawImage(this.DU.Rkb,y,Pa,Xa,ib,Ma,Ta,Xa,ib),this.DU.Rkb=null):null!=this.DU.Rx?e.drawImage(this.DU.Rx,y,Pa,Xa,ib,Ma,Ta,Xa,ib):(Va=this.DU.Pza,e.drawImage(Va.fCa.Kda,Va.qc.Tc*Va.za+y,Va.qc.la+Pa,Xa,ib,Ma,Ta,Xa,ib)))},OEb:function(){null!=this.DU.Pza&&this.DU.Pza.fCa.OEb(this.DU.Pza)}};kb.prototype={start:function(){},fqg:function(e,f,y){this.VHb&&(y.Cy(),this.VHb=!1);this.fI=this.ka+e/64*this.gsb;this.QVa=this.la-f/64*this.hsb;y.Sj(this.fI,this.QVa);return 0},Rbg:function(e,f){return this.fqg(e.x,
e.y,f)},Xpg:function(e,f,y){this.fI=this.ka+e/64*this.gsb;this.QVa=this.la-f/64*this.hsb;y.Ic(this.fI,this.QVa);this.VHb=!0;return 0},pPf:function(e,f){return this.Xpg(e.x,e.y,f)},lpg:function(e,f,y,Va,Ma){e=this.ka+e/64*this.gsb;f=this.la-f/64*this.hsb;y=this.ka+y/64*this.gsb;Va=this.la-Va/64*this.hsb;Ma.$d(1/3*(this.fI+2*e),1/3*(this.QVa+2*f),1/3*(2*e+y),1/3*(2*f+Va),y,Va);this.fI=y;this.QVa=Va;this.VHb=!0;return 0},ncf:function(e,f,y){return this.lpg(e.x,e.y,f.x,f.y,y)},opg:function(e,f,y,Va,Ma,
Ta,Ia){this.fI=this.ka+Ma/64*this.gsb;this.QVa=this.la-Ta/64*this.hsb;Ia.$d(this.ka+e/64*this.gsb,this.la-f/64*this.hsb,this.ka+y/64*this.gsb,this.la-Va/64*this.hsb,this.fI,this.QVa);this.VHb=!0;return 0},FKf:function(e,f,y,Va){return this.opg(e.x,e.y,f.x,f.y,y.x,y.y,Va)},end:function(e){this.VHb&&(e.Cy(),this.VHb=!1)}};f.AscFonts.NEb=zb;f.AscFonts.ETf=function(){this.b9d="undefined"==typeof Float64Array?Array(6):new Float64Array(6);this.X8b="undefined"==typeof Float64Array?Array(6):new Float64Array(6);
this.dbg=!0;this.TYc=!1;this.KJb=1;this.e9b=this.QJb=0;this.Nbc=this.SYc=!1;this.Klb=0;this.a9b=new mb.XDf;this.IVd=0;this.aGa=this.p7=null;this.Ppf=1;this.SDd=this.RDd=-1;this.hya=!1;this.Boa=this.Lra=this.HBa=this.kAa=this.e9d=0;this.V8b=[];this.W8b=[];this.Sv=null;this.HJb=this.ape=this.Phc=!0;this.zwg=e;this.U6b=new rb;this.YVf=function(e,f,y){y=mb.Nje(e,f,y);if(0!=y&&this.Phc){e=mb.Nje(e,f,mb.EXf);if(0!=e)return y;this.Phc=!1;return e}return y};this.pDe=function(){var e=this.b9d;this.SYc?(e[0]=
1,e[1]=0,e[2]=.3090169943749):(e[0]=1,e[1]=0,e[2]=0);e[3]=1;e[4]=0;e[5]=0;this.Tkb()};this.NYf=function(){var e=this.X8b;e[0]=1;e[1]=0;e[2]=0;e[3]=1;e[4]=0;e[5]=0;this.bge()};this.bge=function(){this.HJb=!0;var e=this.X8b;1==e[0]&&0==e[1]&&0==e[2]&&1==e[3]&&(this.HJb=!1,this.Tkb())};this.Tkb=function(){var e=this.b9d,f=this.X8b;mb.aWf(this.p7,65536*(e[0]*f[0]+e[1]*f[2])>>0,65536*(e[0]*f[1]+e[1]*f[3])>>0,65536*(e[2]*f[0]+e[3]*f[2])>>0,65536*(e[2]*f[1]+e[3]*f[3])>>0)};this.w0d=function(e,f,y){f=f+.5>>
0;y=y+.5>>0;var Va=e/this.KJb;if((Va=1.001<Va||.999>Va?!0:!1)||f!=this.QJb||y!=this.e9b)this.QJb=f,this.e9b=y,Va&&(this.KJb=e,this.Tkb()),this.Ppf=this.QJb/72*this.KJb,this.IVd=mb.Oje(this.p7,0,64*e>>0,f,y),this.Dmb()};this.Dmb=function(){this.m$b();this.c$b();this.U6b&&this.U6b.Dmb()};this.c$b=function(){this.V8b=[];this.W8b=[];this.U6b&&this.U6b.c$b()};this.m$b=function(){if(null!=this.Sv&&null!=this.Sv.Qza){var e=this.V8b,f;for(f in e)null!=e[f].fA&&e[f].fA.OEb();e=this.W8b;for(f in e)null!=e[f].fA&&
e[f].fA.OEb()}};this.p5a=function(e,f,y,Va,Ma,Ta){var Ia=this.X8b,Pa=Ia[0]==e&&Ia[1]==-f&&Ia[2]==-y&&Ia[3]==Va;if(Pa&&Ia[4]==Ma&&Ia[5]==Ta)return!1;Ia[0]=e;Ia[1]=-f;Ia[2]=-y;Ia[3]=Va;Ia[4]=Ma;Ia[5]=Ta;Pa||this.Dmb();this.bge();return!0};this.lFf=function(e){var f=mb.aFf(this.p7,e);if(0<f)return f;-1!=this.SDd&&61440>e&&(f=mb.aFf(this.p7,e+61440));return f};this.d6b=function(f,Ta,Ia,Xa,Ma,$a,jb){var Pa=new y;Pa.eig=f;var ib=this.hya?f:mb.aFf(this.p7,f);0>=ib&&!this.hya&&-1!=this.SDd&&61440>f&&(ib=
mb.aFf(this.p7,f+61440));if(0>=ib){if(!0===jb)return null;if(!this.hya&&this.U6b&&(ib=this.U6b.HXf(this,f,Ta,Ia,Xa,Ma,$a)))return ib;if(0<=this.RDd)ib=this.RDd,Pa.zda=zb.Ywc;else return Pa.zda=zb.D8b,Pa.s_c=-1,Pa.dra=(mb.IIg(this.p7)>>6)/2,Pa}else Pa.zda=zb.V5a;Pa.s_c=ib;Pa.Xbg=0;var Xb=this.wWf();if(this.hya||!Ta||this.Nbc||!mb.z2g(f))Xb|=mb.F6c.PIg;if(this.YVf(this.p7,ib,Xb))return Pa;f=null;e!==Xa&&(f=new kb,f.gsb=25.4/this.QJb,f.hsb=25.4/this.e9b,Ma!==e&&(f.ka=Ma),$a!==e&&(f.la=$a));Ma=mb.OIg(this.p7,
Xa,f);if(null==Ma||e!==Xa)return Pa;Xa=65535!=this.aGa.tQf&&800<=this.aGa.$Cg?!0:!1;Pa.dra=Ma.pIc*this.Ppf/this.Boa;this.Nbc&&this.Sv.HFf&&!Xa&&(Pa.dra+=1);Pa.hz.YTa=Ma.vtg>>6;Pa.hz.T7a=Ma.utg>>6;Pa.hz.e0a=Ma.xtg>>6;Pa.hz.ola=Ma.wtg>>6;$a=Pa.cia;$a.Znb=Ma.width>>6;$a.kWb=Ma.height>>6;$a.Ewd=Ma.Wxa>>6;$a.Fwd=Ma.tua>>6;$a.gRc=Ma.voa>>6;$a.Hwd=Ma.MIa>>6;$a.Iwd=Ma.uHa>>6;$a.Gwd=Ma.Nna>>6;if(jb&&0==$a.gRc&&0==Ma.width)return null;if(!Ta){if(Ia&&(Ta=mb.hlg(this.p7,Va))){Xa=mb.glg(this.p7,Ta,!1);Ta=Pa.hz;
f=Xa.data;Ia=Xa.width;jb=Xa.rows;ib=Xa.pitch;Xa={wXc:0,xXc:0,x6f:0,w6f:0};Xb=!1;for(Ma=0;Ma<Ia;Ma++){var Ac=4*Ma+3;for($a=0;$a<jb;$a++,Ac+=ib)if(0!=f[Ac]){Xb=!0;break}if(Xb)break;Xa.wXc++}Xb=!1;for(Ma=Ia-1;0<=Ma;Ma--){Ac=4*Ma+3;for($a=0;$a<jb;$a++,Ac+=ib)if(0!=f[Ac]){Xb=!0;break}if(Xb)break;Xa.x6f++}Xb=!1;for($a=0;$a<jb;$a++){Ac=$a*ib+3;for(Ma=0;Ma<Ia;Ma++,Ac+=4)if(0!=f[Ac]){Xb=!0;break}if(Xb)break;Xa.xXc++}Xb=!1;for($a=jb-1;0<=$a;$a--){Ac=$a*ib+3;for(Ma=0;Ma<Ia;Ma++,Ac+=4)if(0!=f[Ac]){Xb=!0;break}if(Xb)break;
Xa.w6f++}if(null!=yb.p2a)for(f=3,ib=4*(yb.width-Ia),Xb=yb.p2a.data,$a=0;$a<jb;$a++){for(Ma=0;Ma<Ia;Ma++)Xb[f]=0,f+=4;f+=ib}Ta.x8a=Xa}return Pa}Pa.eIa=!0;Ta=mb.hlg(this.p7,Va);if(!Ta||0==Ta.pitch)return Pa;Pa.fA=new cb;Pa.fA.j6a=Ta.left;Pa.fA.kSc=Ta.top;Pa.fA.Coa=Ta.width;Pa.fA.mya=Ta.rows;mb.glg(this.p7,Ta,!0);if(this.Nbc&&this.dbg&&!Xa)for(Pa.fA.Coa++,Ta=Pa.fA.Coa,Ia=Pa.fA.mya,$a=yb.p2a.data,Ma=jb=0;jb<Ia;++jb,Ma+=yb.pitch)for(Xa=Ta-1;0<=Xa;--Xa)0!=Xa&&(f=Ma+4*Xa+3,$a[f]=Ta-1==Xa?$a[f-4]:Math.min(255,
$a[f-4]+$a[f]));Pa.fA.A7f(this.Sv);return Pa};this.lda=function(f){if(0>=f.bI)return!0;var y=0,Va=0;this.HJb&&this.Tkb();for(var Ta=!1===this.hya?this.V8b:this.W8b,Ma=0;Ma<f.bI;++Ma){var Ia=f.eNb(Ma).uSa,jb=Ta[Ia];e==jb&&(Ta[Ia]=this.d6b(Ia,!1),jb=Ta[Ia]);Ia=jb.s_c;var Pa=jb.zda;zb.D8b==Pa?(f.yPc(Ma,Va,0),f.sPc(Ma,0,0,0,0),f.cRb(Ma,zb.D8b),Va+=jb.dra+this.Klb,y=0):(zb.Ywc==Pa?f.cRb(Ma,zb.Ywc):f.cRb(Ma,zb.V5a),this.TYc&&y&&0<Ma&&f.eNb(Ma).zda==f.eNb(Ma-1).zda&&(Va+=this.dhc(y,Ia)),y=f.s_+Va,Pa=f.t_+
0,f.yPc(Ma,f.aia[4]+y*f.aia[0]+Pa*f.aia[2]-f.s_,f.aia[5]+y*f.aia[1]+Pa*f.aia[3]-f.t_),y=jb.cia,f.MGf(Ma,y.Znb,y.kWb,y.gRc,y.Ewd,y.Fwd,y.Gwd,y.Hwd,y.Iwd),f.sPc(Ma,jb.hz.YTa,jb.hz.ola,jb.hz.T7a,jb.hz.e0a),Va+=jb.dra+this.Klb,y=Ia)}f.wBb=Va+f.s_;f.w2b=0+f.t_};this.cc=function(f){if(0>=f.bI)return!0;this.HJb&&this.Tkb();for(var y=0,Va=0,Ta=!1===this.hya?this.V8b:this.W8b,Ma=0;Ma<f.bI;++Ma){var Ia=f.eNb(Ma),jb=Ia.uSa,Pa=Ta[jb];if(e==Pa||null==Pa.fA)Ta[jb]=this.d6b(jb,!0),Pa=Ta[jb];jb=Pa.s_c;var Xa=Pa.zda;
zb.D8b==Xa?(f.yPc(Ma,Va,0),f.sPc(Ma,0,0,0,0),f.cRb(Ma,zb.D8b),Va+=Pa.dra+this.Klb,y=0):(zb.Ywc==Xa?f.cRb(Ma,zb.Ywc):f.cRb(Ma,zb.V5a),this.TYc&&y&&0<Ma&&f.eNb(Ma).zda==f.eNb(Ma-1).zda&&(Va+=this.dhc(y,jb)),y=f.s_+Va,Xa=f.t_+0,f.yPc(Ma,f.aia[4]+y*f.aia[0]+Xa*f.aia[2]-f.s_,f.aia[5]+y*f.aia[1]+Xa*f.aia[3]-f.t_),Ia.cia=Pa.cia,f.sPc(Ma,Pa.hz.YTa,Pa.hz.ola,Pa.hz.T7a,Pa.hz.e0a),Va+=Pa.dra+this.Klb,Ia.eIa=Pa.eIa,Ia.fA=Pa.fA,y=jb)}f.wBb=Va+f.s_;f.w2b=0+f.t_};this.tOd=function(f){this.HJb&&this.Tkb();var y=
f.gM[0],Va=y.uSa,Ta=!1===this.hya?this.V8b:this.W8b,Ma=Ta[Va];if(e==Ma||null==Ma.fA&&!1===Ma.eIa)Ta[Va]=this.d6b(Va,!0),Ma=Ta[Va];if(Ma)if(Va=Ma.zda,y.zda=Ma.zda,zb.D8b==Va)y.Pz=0,y.Xy=0,y.GJa=0,y.jBa=0,y.ZTa=0,y.FJa=0;else{Va=f.s_;Ta=f.t_;var Ia=f.aia;y.Pz=Ia[4]+Va*Ia[0]+Ta*Ia[2]-f.s_;y.Xy=Ia[5]+Va*Ia[1]+Ta*Ia[3]-f.t_;y.cia=Ma.cia;y.eIa=Ma.eIa;y.fA=Ma.fA;f.wBb=Ma.dra+this.Klb+f.s_;f.w2b=f.t_}};this.Z0=function(f,y){this.HJb&&this.Tkb();var Va=!1===this.hya?this.V8b:this.W8b,Ta=Va[f];e==Ta&&(Va[f]=
this.d6b(f,!1,y),Ta=Va[f]);return Ta};this.xWf=function(e,f,y,Va){this.HJb&&this.Tkb();this.d6b(e,!1,!1,f,y,Va)};this.oFf=function(e,f){var y=e.bI;if(!(0>=y))for(var Va=0;Va<y;++Va){var Ma=e.gM[Va],Ta=e.s_+25.4*Ma.Pz/this.QJb,Ia=e.t_+25.4*Ma.Xy/this.e9b;f.Gj();this.xWf(Ma.uSa,f,Ta,Ia);f.Xt();f.Hu()}};this.wWf=function(){return this.Phc&&this.ape?this.Sv.B_d:mb.EXf};this.dhc=function(e,f){return mb.JIg(this.p7,e,f)>>6};this.NHa=function(e){this.hya!=e&&(this.hya=e)};this.KGf=function(e){this.Klb=e};
this.sXf=function(){return this.Nbc?!0:-1!=this.aGa.nHa.indexOf("Bold")?!0:!1};this.xXf=function(){return this.SYc?!0:-1!=this.aGa.nHa.indexOf("Italic")?!0:!1};this.OGf=function(e){this.SYc!=e&&(this.Dmb(),this.SYc=e,this.pDe())};this.NGf=function(e){this.Nbc!=e&&(this.Dmb(),this.Nbc=e)};this.w_d=function(){return 0==this.IVd};this.D$a=function(){return this.kAa};this.kWa=function(){return this.HBa};this.UH=function(){return this.Lra};this.OYd=function(){this.ape=this.Phc=!0};this.lug=function(){var e=
this.aGa,f=[];f.push(e.MUa);65535!=e.tQf?(f.push(e.xcg),f.push(-e.ycg)):(f.push(e.ryg),f.push(e.syg));return f};this.kLg=function(e,f){this.p7=e;this.aGa=new mb.gHg;this.aGa.load(this.p7);this.Boa=this.aGa.MUa;this.kAa=this.aGa.W7;this.HBa=this.aGa.X_;this.Lra=this.aGa.height;if(f.MFf&&65535!=this.aGa.tQf)if(f.EOd){var y=this.aGa.xcg,Va=-this.aGa.ycg;if(0!=(this.aGa.YCg&770703360)){var Ma=.3*(y-Va)>>0;y+=Ma+1>>1;Va-=Ma>>1}this.aGa.height<y-Va&&(this.kAa=y,this.HBa=Va,this.Lra=y-Va)}else 128==(this.aGa.VCg&
128)&&(this.kAa=this.aGa.vcg,this.HBa=this.aGa.wcg,this.Lra=this.aGa.vcg-this.aGa.wcg+this.aGa.XCg);this.e9d=this.aGa.j9b;this.RDd=this.aGa.ZCg;this.SDd=this.aGa.WCg;this.IVd=mb.Oje(e,0,64*this.KJb,0,0);this.NYf();this.pDe();!0===f.TYc&&(this.TYc=0!=(this.aGa.z0&64)?!0:!1);if(0!=this.aGa.PPf.length)for(this.zwg=[],e=this.aGa.PPf.length-1;0<=e;e--)this.zwg[this.aGa.PPf[e]>>6]=!0}};f.AscFonts.$Jb()})(window);"use strict";
(function(f){function e(){this.tM=Ia.aIg();this.cGa=null;this.sQf=function(e,f){e=Ia.$Vf(this.tM,e,f);if(!e)return null;f=new Ia.ETf;f.kLg(e,this.cGa);return f.w_d()?f:null};this.y$d=function(e,f){f=e&&f?Ia.FLg:Ia.ELg;this.cGa.B_d=e?Ia.RJg:Ia.EXf;Ia.ZIg(this.tM,f)}}var Ia=f.AscFonts;f.AscFonts.gLf=function(f){var Xa=new e;Xa.cGa=f;Xa.y$d(f.LRd,f.MRd);f.rFb=Xa;Ia.F$f()};f.AscFonts.a_g=function(){};f.AscFonts.$Jb()})(window);
